### ISSUE TITLE
Allow non-self-citation standout tags to be used 

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-news#104]
There are two ways to use standout tags;
- self-citing (already implemented)
- non self-citing

To use this latest way we'd have to implement a way to "interfere" with links in WordPress. Although I think it is quite hard to implement, it could show to be a valuable feature (also for non-news website, thus creating a broader public for News SEO).

Documentation can be found here: https://support.google.com/news/publisher/answer/191283?hl=en

**Comment by jdevalk** [comment]
Nah, let's not, don't see much use case for it.
