### ISSUE TITLE
Do not allow more than 7 standout tags to be active/used

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-news#105]
From [Google's documentation](https://support.google.com/news/publisher/answer/191283?hl=en):
> You haven't used standout on your own articles more than seven times in the past calendar week.

We currently allow more than 7 standout tags to be active, although we show that more are active.
![edit_post_ _theme_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/5246277/0f7a0834-7967-11e4-929d-275b23d89816.png)

Since Google may remove a website from Google News when they feel the standout tag is abused, I think we should be more careful in allowing more than 7 standout tags to be added/used.

**Comment by omarreiss** [comment]
We've added an extra note to explain the standout tags here: https://github.com/Yoast/wpseo-news/pull/111/files?w=1#diff-ef8b0403f606907afaa6b03378e64a55R236

Responsibility of the user.
