### ISSUE TITLE
Do Not Display Duplicate Keywords in News Sitemap

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-news#106]
Sitemap shows post level keywords, post tags, and default keywords. This can lead to duplicates if the same keyword/phrase is used in multiple places.

Example
Post level keywords: keyboards, technology, another keyword
Post tags: keyboards, technology
Default keywords: technology

Current output: keyboards, technology, another keyword, keyboards, technology, technology
Preferred output: keyboards, technology, another keyword

User suggestion via support ticket #31475

**Comment by andizer** [comment]
@amboutwe This should be fixed with PR #110
