### ISSUE TITLE
Translation errors in editor's pick rss button

### ISSUE THREAD

**Issue by omarreiss** [Yoast/wpseo-news#128]
The editor's pick rss button comes out strangely for the 

![screen shot 2015-03-24 at 13 00 33](https://cloud.githubusercontent.com/assets/1488816/6801259/6cc09f40-d226-11e4-955e-1d75199bc76b.png)

This is due to an incorrect translation on translate.yoast.com:

![screen shot 2015-03-24 at 13 03 05](https://cloud.githubusercontent.com/assets/1488816/6801262/6fc42acc-d226-11e4-8f2d-73c602b524bb.png)

I also found a plain translation mistake:

![screen shot 2015-03-24 at 13 09 20](https://cloud.githubusercontent.com/assets/1488816/6801348/1e301cce-d227-11e4-87c1-f373e0a36960.png)

@tacoverdo could you fix this (I forgot my login :relaxed: )?

**Comment by tacoverdo** [comment]
Fixed at https://translate.yoast.com/projects/news-seo/nl/default?filters[status]=either&filters[original_id]=3012&filters[translation_id]=94052
