### ISSUE TITLE
Add support for access-tag

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-news#129]
The <access> tag specifies whether an article is available to all readers, or only to those with a free or paid membership to your site. See documentation at [https://support.google.com/news/publisher/answer/93992?hl=en](https://support.google.com/news/publisher/answer/93992?hl=en).

**Comment by AskKim** [comment]
Please let customer in # 77327 know when this is closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 159105 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
@tacoverdo and @Pcosta88 - This article only explains the `<genres>` content types. I assume you mean: https://support.google.com/news/publisher/answer/4582731#subscription? If not, please clarify the issue with the Google News explanation and more information if possible.

**Comment by benvaassen** [comment]
@CarolineGeven - Correct. User replied: 

> I have this feed
> > https://www.infochretienne.com/editors-pick.rss
> 
> I followed the google recomendations
> > https://support.google.com/news/publisher/answer/1407682?hl=en#submit
> 
> The feed should have a <logo> tag wich is a requierement but your feed as an <image> tag. So my feed is not validated by Google because the <logo> tag is not found.
> 
> Your feed looks like an atom feed with the specification of a RSS feed.
> 
> I should also be able to customize the <access> tag for each post (https://support.google.com/news/publisher/answer/4582731?hl=fr&ref_topic=3189759) and I don't see the option for that.

**Comment by moorscode** [comment]
There is a definition about this element in the sitemap schema.

```xml
<xsd:element name="access" minOccurs="0">
<xsd:annotation>
<xsd:documentation>
Accessibility of the article. Required if access is not open, otherwise this tag should be omitted.
</xsd:documentation>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:enumeration value="Subscription"/>
<xsd:enumeration value="Registration"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
```

```xml
<xsd:element name="genres" minOccurs="0">
<xsd:annotation>
<xsd:documentation>
A comma-separated list of properties characterizing the content of the article, such as "PressRelease" or "UserGenerated". For a list of possible values, see: http://www.google.com/support/news_pub/bin/answer.py?answer=93992 Required if any genres apply to the article, otherwise this tag should be omitted.
</xsd:documentation>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:pattern value="(PressRelease|Satire|Blog|OpEd|Opinion|UserGenerated)(, *(PressRelease|Satire|Blog|OpEd|Opinion|UserGenerated))*"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
```

Both the `access` and `genres` can be set per entry.

There is very little documentation about on any Google documentation pages.

**Comment by jdevalk** [comment]
I'm fine with adding this.

**Comment by jono-alderson** [comment]
Looks like this has been deprecated.
