### ISSUE TITLE
Escape HTML for content wrapped in CDATA tags?

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-news#131]
We received the following report from a customer.
> I had a post with the title "Wells Fargo & Co. Blog Post"
> Which was being reinterpreted inside the XML to "Wells Fargo &amp; Co. Blog Post" automatically.
> Example: 		`<news:title><![CDATA[Wells Fargo &amp; Co. Blog Post]]></news:title>`
> Within CDATA the transformation to &amp; is not necessary and may actually create issues since there is no processing within CDATA
> So, shouldn't it be 		`<news:title><![CDATA[Wells Fargo & Co. Blog Post]]></news:title>`

@jdevalk / @omarreiss: Should we change the way this is currently handled?

**Comment by jdevalk** [comment]
Yes, the customer is right. It's actually a bug.
