### ISSUE TITLE
NaN in news-sitemap - causes by loading wrong XSL

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-news#132]
After upgrading from News SEO 2.2.1 to 2.2.3 the following errors show in the news sitemap, possibly causing problems in Google News:
![xml_sitemap](https://cloud.githubusercontent.com/assets/5147598/7314498/599518b8-ea65-11e4-926d-30321a3473bb.png)

Possible cause is loading the wrong xsl-file, 
`<?xml-stylesheet type="text/xsl" href="//clean.dev/main-sitemap.xsl"?>`
instead of 
`<?xml-stylesheet type="text/xsl" href="//clean.dev/wp-content/plugins/wpseo-news/assets/xml-news-sitemap.xsl"?>`

WordPress version 4.2
WordPress SEO version 2.1.1

**Comment by jdevalk** [comment]
Use the source, @tacoverdo  :)

The wrong XSL is being loaded.

**Comment by jdevalk** [comment]
Will probably give a lot of support issues but shouldn't give any issues with Google News itself. Might want to fix though, probably easy enough.
