### ISSUE TITLE
Does not generate the news sitemap

### ISSUE THREAD

**Issue by manuiglesias** [Yoast/wpseo-news#134]
The plugin does not generate the sitemap with the latest version installed

**Comment by luukdv** [comment]
Same issue here. Note: after the update there's a request for `http://cdn.yoast.com/js/jquery.tablesorter.min.js`, which doesn't seem to exist.

**Comment by tacoverdo** [comment]
This is not a valid bug report, but a support request. Please contact pluginsupport@yoast.com for support.
