### ISSUE TITLE
News Sitemap Hard Coded For 1000 Limit

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-news#137]
"LIMIT 0, 1000" seen [here](https://github.com/Yoast/wpseo-news/blob/b28c1d0de853647f1d83e559288a234cd7821253/classes/class-sitemap.php#L131)

Current Outcome: One news sitemap in the sitemap index with limit of 1000 articles.

Problem: All articles are not included when site publishes more than 1000 articles in two days. News sitemap does not account for the limit entered into the WPSEO sitemap setting.

Expectation: Limit would match the limit entered into the WPSEO sitemap setting and create multiple sitemaps when number of news articles exceed the limit.

[User submitted image](https://www.evernote.com/shard/s198/sh/ca1b2e99-6345-443e-8122-788fb4275484/d5b51ff06d7eac24e0881f42f5120ad1)

I also noticed a second sitemap is created but it's identical to the first one and not listed in the sitemap index.

**Comment by tacoverdo** [comment]
Please inform the customer of conversation # 46344 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
This issue unfortunately requires more debugging than giving the max-entries settings of WPSEO instead of the limit 1000. The sitemap does not get all news articles when the max-entry is set and does not properly create more news sitemaps. This needs thorough debugging.

**Comment by CarolineGeven** [comment]
Unfortunately we're not able to fix this at short notice. Currently we're focusing on issues that affect many users. We've concluded that this issue is not experienced by many users, therefore we are not able to fix this short-term. However, if more users are affected by this bug, we'll of course revisit this issue.

**Comment by andizer** [comment]
I saw this issue and looked at the [documentation Google provides].(https://support.google.com/news/publisher/answer/74288?hl=en#sitemapguidelines). 

There cannot be more than 1000 urls in a sitemap:
> A News Sitemap can contain no more than 1,000 URLs. If you want to include more, you can break these URLs into multiple Sitemaps, and use a Sitemap index file to manage them. Use the XML format provided in the Sitemap protocol. Your Sitemap index file shouldn't list more than 50,000 Sitemaps. These limits help ensure that your web server isn't overloaded by serving large files to Google News.

**Comment by CarolineGeven** [comment]
Thanks @andizer. I will close this issue and label it as a wontfix.

**Comment by Pcosta88** [comment]
Opened it as a feature request:

related: https://github.com/Yoast/wpseo-news/issues/311
