### ISSUE TITLE
[Feature Request] Add Support For Googlebot-News 'noindex' Meta

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-news#138]
Google can index posts in Google News even though they are not listed in the News Sitemap. Customer requested that we add a Google News specific noindex option as specified [here](https://support.google.com/news/publisher/answer/93977?hl=en).

`<meta name="Googlebot-News" content="noindex, nofollow">`

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 59792 when this issue has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 101427 when this conversation has been closed.
