### ISSUE TITLE
W3C Validation Error on <link Attribute "original-source"

### ISSUE THREAD

**Issue by malerwhick** [Yoast/wpseo-news#140]
The W3C validator marks the Tag in head section <link rel="original-source" as an error.

Error Line 46, Column 58: Bad value original-source for attribute rel on element link: The string original-source is not a registered keyword.
<link rel="original-source" href="https://www.weka.de/" />

There is a Keyword original-source for the tag <meta:
<meta rel="original-source" href="https://www.weka.de/" />

**Comment by tanng** [comment]
My site also has this bug

**Comment by monbauza** [comment]
![image](https://cloud.githubusercontent.com/assets/9658774/11091051/615d1234-8877-11e5-87b8-6214ffc8f69f.png)

Please inform the customer of conversation # 83463 when this issue has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 130679 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 150276 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 83463 when this issue has been closed.

**Comment by CarolineGeven** [comment]
'<link rel="original-source"' should be `<meta name: original-source`
