### ISSUE TITLE
NaN% in sitemap

### ISSUE THREAD

**Issue by luukdv** [Yoast/wpseo-news#144]
From time to time, the news sitemap doesn't generate the usual data (keywords, genres, images, publication date) but it shows the following:

![screen shot 2015-07-13 at 09 38 13](https://cloud.githubusercontent.com/assets/5585947/8644939/5e9f09d2-2943-11e5-909b-275fb6cbc0b0.png)

**Comment by tacoverdo** [comment]
Possibly related to #132.

@luukdv What version of News SEO are you using? And what version of WordPress?

**Comment by luukdv** [comment]
News SEO: 2.2.5
WordPress: 4.2.2

**Comment by CarolineGeven** [comment]
Closing this as this issue seems to be fixed in the current version.
If it still persists, please create a new issue with the needed information to reproduce this.
