### ISSUE TITLE
PHP Warning when also using bbPress

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-news#146]
When using WordPress SEO (v2.2.1), News SEO (v2.2.5) and bbPress (v2.5.7) the following warning occurs:
```
PHP Warning: in_array() expects parameter 2 to be array, null given in /nas/wp/www/cluster-10589/ehotelier/wp-content/plugins/bbpress/includes/common/functions.php on line 1446
```

This problem has been described on the [bbPress support forums](https://bbpress.org/forums/topic/news-seo-bbpress-conflict/) where the following workaround was found:
> If you comment out this out of the News SEO plugin file `class-meta-box.php`
> `add_filter( 'add_extra_wpseo_meta_fields', array( $this, 'add_meta_fields_to_wpseo_meta' ) );`
> In the News SEO plugin the issue is resolved and no notices are displayed.
>
> It appears to be related to `pre_get_posts` being used in WordPress SEO by Yoast, this was picked up in the WordPress Core ticket https://core.trac.wordpress.org/ticket/31231

**Comment by Volnus** [comment]
Any status on this fix @tacoverdo

**Comment by fergusga** [comment]
Any update would be great, I have had to take down my forum until this is resolved.

**Comment by mckolt** [comment]
Have the same problem, any update ?

**Comment by AskKim** [comment]
Please notify customer ticket # 77445 when this is solved.

**Comment by AskKim** [comment]
Please notify customer ticket # 79581 when this is solved.

**Comment by neilgee** [comment]
I just got this issue but it only occurred when upgrading a site to PHP 5.6(previously on 5.4).

Warning: in_array() expects parameter 2 to be array, null given in /home2/tabbangy/public_html/tabban/wp-content/plugins/bbpress/includes/common/functions.php on line 1446

I did have Yoast SEO installed but on deactivation the error still persists ( i don’t have NEWS SEO).

Reverting back to 5.4 clears the error.

https://bbpress.org/forums/topic/news-seo-bbpress-conflict/#post-168172

**Comment by AskKim** [comment]
Customer in support ticket # 89888 is still experiencing this issue even after revering PHP to 5.4.  I'll get admin details so we can take a closer look at this.
