### ISSUE TITLE
[Feature Request] Remove News Sitemap From Index When Empty

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-news#147]
Google Search Console gives a 'Missing XML tag' error when the news sitemap is empty. It would be nice that the news sitemap didn't appear in the sitemap index when there aren't any news items or at least have the possibility to disable the news sitemap. Right now, the only way to disable the news sitemap is to deactivate the plugin.

**Comment by matfricker** [comment]
Yes, I think this would be a handy feature as we are also getting errors in Search Console on at least two websites that we currently use. Any updates on the situation?

**Comment by AskKim** [comment]
Please let client in # 91052 know when this is closed

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 174801 when this conversation has been closed.
