### ISSUE TITLE
jquery.tablesorter.min.js not available

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-news#148]
News SEO tries to load `jquery.tablesorter.min.js` from http://cdn.yoast.com/js/jquery.tablesorter.min.js, however that file no longer exists, causing a JavaScript warning on every installation of News SEO. 

This results in two errors.
![developer_tools_-_http___clean_dev_news-sitemap_xml](https://cloud.githubusercontent.com/assets/5147598/8984143/ffe50780-36cf-11e5-917a-fe24eb6dfa04.png)

**Comment by paxperscientiam** [comment]
My comment here is more meta than anything else. That is, for a temporary workaround, I would recommend that users grab an older copy of jquery.tablesorter.min.js from the Wayback Machine.

It worked for me.
