### ISSUE TITLE
Clear sitemap transient on deactivation/activation

### ISSUE THREAD

**Issue by andizer** [Yoast/wpseo-news#151]
When there is a cached sitemap there is nothing happening when news seo plugin is activated. The sitemap for news seo won't appear in the sitemap. Only when transient is expired or emptied this sitemap will be visible in the sitemap.

The same should be happening when news seo is being deactivated; In that case we want the sitemap item to be removed from the sitemap index.

**Comment by CarolineGeven** [comment]
Closing as this issue seems to be fixed in the current version. If it is still occuring, please create a new issue report.
