### ISSUE TITLE
Empty sitemap causes errors in Search Console?

### ISSUE THREAD

**Issue by uprise10** [Yoast/wpseo-news#154]
It appears the Google console gives syntax errors when the News XML sitemap is empty.

XML from empty sitemap:

```xml

<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="//www.website.om/main-sitemap.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
</urlset>
<!-- XML Sitemap generated by Yoast SEO -->
```

Screenshot from error in Search Console: http://upload.uprise.nl/1gKJ1. It appears that Google expects the <url> field, but obviously it isn't there.

Should the error message just be ignored, or is there some error in the syntax for empty News sitemaps?

**Comment by amboutwe** [comment]
Related to #147?

**Comment by omarreiss** [comment]
The question remains, but we think we should simply not show the sitemap if there are no posts to list. See #147.
