### ISSUE TITLE
Don't fool travis, just fix the issue

### ISSUE THREAD

**Issue by andizer** [Yoast/wpseo-news#158]
We have to find a solution for [this trick](https://github.com/Yoast/wpseo-news/blob/trunk/classes/class-sitemap.php#L125) to fool [Travis codestyle](https://travis-ci.org/Yoast/wpseo-news/jobs/87887498#L242).

Just preparing with the values will result in escaping the values for `IN` and that results in an empty resultset.

**Comment by CarolineGeven** [comment]
This issue seems to be fixed in the current version. If it's not, please create a new issue.
