### ISSUE TITLE
default Genre and default keywords work in different ways. 

### ISSUE THREAD

**Issue by boblinthorst** [Yoast/wpseo-news#162]
Using:
WordPress SEO News (2.2.5)
Wordpress version 4.4
Yoast SEO (branch 3.0)
Both chrome and firefox

Other active plugins and themes:
Twenty Fifteen

This is not a bug. It is not intuitive however. 

The default genre takes the place of the genre if none is selected. (multiple genres is possible). 
The default keywords are always added to the list of keywords. 

You'd expect both to work in the same way. If this is as intended, this is a non-issue.

**Comment by atimmer** [comment]
We should fix this by just adding a line of copy under the field with:
`Keyword "x, y, z" are always included as they are set as defaults for the site." (Then link it to the settings page where this setting can be changed.)

**Comment by jdevalk** [comment]
As news keywords are gone, this can be closed.
