### ISSUE TITLE
Default keywords don't check amount of keywords added

### ISSUE THREAD

**Issue by boblinthorst** [Yoast/wpseo-news#163]
Using:
WordPress SEO News (2.2.5)
Wordpress version 4.4
Yoast SEO (branch 3.0)
Both chrome and firefox

Other active plugins and themes:
Twenty Fifteen

The metabox news part has a reminder and a warning to deter users from adding more than ten keywords. Apparently this is a limit users should stay under (users are not actively prevented from adding more, it's merely a strong suggestion). 
## 
## 
## 

This limit isn't implemented in the news seo page however. A user can add  default keywords there without the warning they're adding too much. 
## 
## 
## 

The combination of post specific keywords and default keywords also aren't checked together. So the combination of the two can make it so users have posts with more than the advised limit of ten without a warning. 

![issue 5 deel 3](https://cloud.githubusercontent.com/assets/11849359/10905360/fb9cce0c-8219-11e5-9607-fad9e03a881c.png)

steps to reproduce:
1: create a post
2: navigate to the news SEO tab under addons.
3: Add keywords seperated by commas (notice the warning to stay under ten keywords and the text becoming red when too many keywords have been added). 
4: publish the post.
5: navigate to the news SEO page (a tab in the yoast SEO menu). 
6: Add as many keywords as you like. Under no circumstance will you receive a warning). 
7. save the changes to the default keywords. 
8: Check the XML news sitemap to see a post with more keywords than yoast advises without any warnings received on the way.

**Comment by jdevalk** [comment]
As news keywords are gone, this can be closed.
