### ISSUE TITLE
Fatal: Access level

### ISSUE THREAD

**Issue by diedexx** [Yoast/wpseo-news#165]
`Fatal error: Access level to WPSEO_News_Meta_Box::$options must be protected (as in class WPSEO_Metabox) or weaker in /srv/www/wordpress-default/wp-content/plugins/wpseo-news/classes/class-meta-box.php on line 3`

How to reproduce:
1. Install News SEO
2. Enable News SEO
3. Install Yoast SEO
4. Enable Yoast SEO

Using:
- Wordpress version 4.3.1
- WordPress SEO News (2.2.5)
- Yoast SEO (branch 3.0 - Beta 3)
- Safari

Other active plugins and themes:
- Local SEO for Yoast SEO (1.3.8)
- Twenty Fifteen

**Comment by diedexx** [comment]
Also works the other way around. Enable Yoast SEO then News SEO.

**Comment by andizer** [comment]
Is fixed in #166, just forgot to made the pull.

**Comment by diedexx** [comment]
Fixed in YoastSEO
