### ISSUE TITLE
Dead link in XML sitemap

### ISSUE THREAD

**Issue by diedexx** [Yoast/wpseo-news#168]
![screen shot 2015-11-04 at 14 37 00](https://cloud.githubusercontent.com/assets/5352634/10939397/a3b00586-8301-11e5-8505-53da3f2f6eef.png)

The **`here`** link is dead.

Steps to reproduce:
1. Go to the News SEO settings page
2. Click the `XML News sitemap`button.

**Comment by CarolineGeven** [comment]
@diedexx Can you check if this is a regression?

**Comment by diedexx** [comment]
Also dead in 2.2.5 (master)
