### ISSUE TITLE
Unchecking posts from the exclude Post type for XML sitemap setting remembers excluded categories

### ISSUE THREAD

**Issue by diedexx** [Yoast/wpseo-news#169]
Assuming that:
Posts will always be displayed in the sitemap by default unless their category is excluded in the settings.
Posts will still be shown in the sitemap when the `Posts` checkbox under the `include in News Sitemap` setting is not checked. (I will make another issue about that later since it's not clear to the user if this should always be the case.)

Steps to reproduce:
1. Create a post and leave it uncategorized.
2. Go to the News SEO settings page.
3. Save the settings as shown below.
![screen shot 2015-11-04 at 16 22 11](https://cloud.githubusercontent.com/assets/5352634/10942395/3de3d69c-8310-11e5-892f-edb8768ea8cc.png)
4. If you check the XML News sitemap (click the button at the top of the settings page) your created post will be shown in the sitemap. (as it should)
5. Now check the `Uncategorized (x posts)` checkbox and hit `save changes`.
6. If you check the XML News sitemap your created post will _not_ be included. (as it should).
7. Now uncheck the `Posts` checkbox (set in step 3)  while leaving the `Uncategorized (x posts)` checked and hit `save changes`.
8. If you check the XML News sitemap again, the posts are all gone (As if all uncategorized posts are still excluded)
9. if you hit `save changes` again without changing any settings and check the XML News sitemap again, the posts have reappeared.  

It seems like when you hit save at step 7 the plugin still processes the `post categories to exclude` even though the `posts` checkbox is unchecked.

**Comment by CarolineGeven** [comment]
@diedexx can you check if this is a regression?

**Comment by diedexx** [comment]
Not regression.

Tested on :
Yoast SEO 3.0 beta 7 with News trunk
Yoast SEO 3.0 beta 7 with News master
Yoast SEO master with News master

**Comment by atimmer** [comment]
This should be fixed by #170
