### ISSUE TITLE
Disable News sitemap when Yoast SEO sitemap is disabled

### ISSUE THREAD

**Issue by diedexx** [Yoast/wpseo-news#172]
When `check this box to enable XML sitemap functionality` is unchecked, all settings related to the xml sitemap in the Yoast SEO plugin itself are hidden.
![screen shot 2015-11-17 at 17 32 32](https://cloud.githubusercontent.com/assets/5352634/11217565/34765594-8d51-11e5-81a2-5f40247b9435.png)

But, you can still click the `XML News sitemap` button in the New SEO settings (which results in a 404).
![screen shot 2015-11-17 at 17 34 11](https://cloud.githubusercontent.com/assets/5352634/11217610/6f816fc0-8d51-11e5-9de9-d9549cb8c21c.png)
## Using
- WordPress 4.3.1
- Yoast SEO 3.0

**Comment by moorscode** [comment]
No customer issues have been reported, this use-case is too low to do anything with. Closing accordingly.
