### ISSUE TITLE
[Feature Request] Add support for schema.org Article markup

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-news#179]
[schema.org Article markup](http://schema.org/Article)

This will apparently increase the chances of appearing as "In-Depth article" in Google News
https://support.google.com/webmasters/answer/3280182?hl=en
https://support.google.com/news/answer/1217612?hl=en

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 236784 when this conversation has been closed.

**Comment by rmarcano** [comment]
The Article schema markup is also useful in helping articles receive SERP features like the Top Stories carousel. 
https://developers.google.com/search/docs/data-types/articles

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 304141 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 436609 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 438618 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 449767 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 483786 when this conversation has been closed.

**Comment by jono-alderson** [comment]
Fixed by https://github.com/Yoast/wordpress-seo/pull/12456

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 489387 when this conversation has been closed.

**Comment by jono-alderson** [comment]
This is live now, and can be customized via our schema API @ https://developer.yoast.com/schema-documentation/api/
