### ISSUE TITLE
punctuation in news keywords

### ISSUE THREAD

**Issue by diedexx** [Yoast/wpseo-news#188]
According to the [documentation provided by Google](https://support.google.com/news/publisher/answer/68297?hl=en) comma's are the only form of punctuation. At this moment, news SEO accepts all kinds of punctuation.

Using
Yoast SEO 3.1 RC
News SEO trunk

**Comment by CarolineGeven** [comment]
We should make sure we only accept commas and filter out all other forms of punctuation
