### ISSUE TITLE
Add HS beacon

### ISSUE THREAD

**Issue by omarreiss** [Yoast/wpseo-news#190]
If premium is not active, news SEO should add de HS beacon to it's own settings page. If it's easier, the beacon could even be added to all settings pages.

**Comment by atimmer** [comment]
@tacoverdo Could you provide a list of articles you want to show as suggestions to the user when they click the beacon?

There can be max 5 pages. On all the current Yoast SEO pages only 2 or 3 articles are suggested.

**Comment by tacoverdo** [comment]
Please include the following articles:

1. http://kb.yoast.com/article/110-configuration-guide-for-news-seo
2. http://kb.yoast.com/article/133-publication-date-time-in-the-news-xml-sitemap
3. http://kb.yoast.com/article/36-my-sitemap-is-blank-what-s-wrong

**Comment by jcomack** [comment]
Acceptance done :+1:
