### ISSUE TITLE
Meta News 10 keywords limit error displayed with 9 keywords

### ISSUE THREAD

**Issue by afercia** [Yoast/wpseo-news#204]
To reproduce, first properly enqueue the JS files, see #203. Then enter keywords separated by commas in the field in the screenshot below:
![screen shot 2016-03-16 at 14 04 57](https://cloud.githubusercontent.com/assets/1682452/13813196/864fb24c-eb80-11e5-9dc3-8da11a911d0a.png)
Given how `split()` works, the JS check should check for length greater then 10 while it currently checks for 9, see in `post-edit.js`:
`if ($(this).val().split(',').length > 9) ...`

**Comment by moorscode** [comment]
The problem in the test is that you have an extra `,` at the end making it 10 items on the split.
We should remove empty elements from the list created by splitting on the `,`.

**Comment by afercia** [comment]
Well, actually to type the 10th term you have to type a comma, no? :) Would be the same if I typed
`...nine,ten`
