### ISSUE TITLE
create ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-news#206]
GitHub recently added a new feature that lets you set a template for new issues. 
Please add `ISSUE_TEMPLATE.md` for this repository.

Documentation: https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by omarreiss** [comment]
There is an ISSUE_TEMPLATE.md [here](https://github.com/Yoast/wpseo-news/blob/trunk/.github/ISSUE_TEMPLATE.md)
