### ISSUE TITLE
Genre set to None causes an error in GSC when using a non-English language

### ISSUE THREAD

**Issue by monbauza** [Yoast/wpseo-news#211]
When English is used and Genre is set to None, the news sitemap doesn't include the tag **news:genres**
However, when a non-English language is used and the Genre is set to None, the news sitemap does include the tag **news:genres** with the translataion of the word None (i.e. Keine, Ninguno, Nessuno, etc.)

GSC seems to complain about this tag

**English**

![image](https://cloud.githubusercontent.com/assets/9658774/15206723/91dbabca-1821-11e6-9ad9-2e2430452e11.png)
![image](https://cloud.githubusercontent.com/assets/9658774/15206769/eecc3f84-1821-11e6-87e4-f375e4b4bc82.png)

**German**

![image](https://cloud.githubusercontent.com/assets/9658774/15206787/0e676fbc-1822-11e6-9dde-e97f144eb348.png)

**Comment by monbauza** [comment]
Please inform the customer of conversation # 118262 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 115734 when this conversation has been closed

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 121986 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 126482 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 123820 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 127550 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 128192 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 130979 when this conversation has been closed.

**Comment by boblinthorst** [comment]
merged pull request of @andizer , so issue should be solved.
