### ISSUE TITLE
Individual Post/Page Genre not override Default

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#216]
**What Was expected**
When an individual genre was selected on a post or page it would override the default genre. 

**What happened Instead**
The post/page genre did not override the default genre and did not appear in the News SEO sitemaps' meta-data.

**Steps to Reproduce**
1.Select a default genre. In this example, "Press-Release" has been selected.

![screen shot 2016-05-25 at 3 05 21 pm](https://cloud.githubusercontent.com/assets/8238074/15552814/34393686-228a-11e6-8865-12f7a2eb1227.png)

2.Select a post and make the post's genre something else. Update the post. In this example the post's name is "Video Custom Field Test" and the genre is "op-ed".

![screen shot 2016-05-25 at 3 07 40 pm](https://cloud.githubusercontent.com/assets/8238074/15552911/a6ed97bc-228a-11e6-8b94-84b1c86d787e.png)

3.Check sitemap for "Op-Ed", it does not appear

![screen shot 2016-05-25 at 3 07 01 pm](https://cloud.githubusercontent.com/assets/8238074/15552932/c0054196-228a-11e6-95e4-4de5e8c511bd.png)

4.Check meta data in the source-code of post. Notice that "press-release" has not been overridden

![screen shot 2016-05-25 at 3 15 37 pm](https://cloud.githubusercontent.com/assets/8238074/15553115/a8530f1e-228b-11e6-8520-d0d0c745c40d.png)

**Notes:** 
Tested with all genre types on a post. They all result in the same outcome. 
Tested on a new post. It resulted in the same outcome.
Tested on pages. It resulted in the same outcome.

**Tech Specs:**
WordPress: 4.5.2
Yoast SEO Premium: 3.2.5
News SEO: 3.2

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 121986 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 125234 when this conversation has been closed.

**Comment by monbauza** [comment]
I tested on my website and got the following notice:

**Notice: Undefined index: _yoast_wpseo_newssitemap-genre in /home/coompone/public_html/test.coompone.com/wp-content/plugins/wordpress-seo-premium/inc/class-wpseo-meta.php on line 692**

A customer also provided the following feedback:

Detailed description of the cause:

1. When generating XML entry for post function get_item_genre() (class-sitemap.php@467) gets data from WPSEO_Meta (first line of function) but gets empty value (even tough in DB there is a serialized value (a:1:{i:0;s:12:"pressrelease";}).
2. Following: inside get_value() method of WPSEO_Meta (class-wpseo-meta.php) on line 692 you're getting value for $field_def variable which is set to null NULL, as there is no "_yoast_wpseo_newssitemap-genre" (self::$meta_prefix . $key) element in self::$fields_index.
3. Reason for this lies in class WPSEO_News_Meta_Box in its contructor which adds filter for "add_extra_wpseo_meta_fields" only when called for "post.php" and "post-new.php" and not for "index.php" ($pagenow value.when called from news-sitemap.xml).

Adding "index.php" to this "if" resulted in generating news sitemap with correct genres (default when post-specific were not specified). At this moment I haven't found other $pagenow values that should be included there but I hope you'll know better.
