### ISSUE TITLE
Google News Support Thinks CDATA Might Cause Sitemap Errors

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-news#218]
Google News error: `Unexpected publication name`

From Google News Support (relevant snippet only):
> The site name appearing for your site in our record is "SITE NAME" whereas the site name updated in your sitemap is "![CDATA[SITE NAME ]]". Please check that the publication name in your Sitemap exactly matches the publication name displayed for your articles in Google News.

Could CDATA cause a mismatch of the site name? Is CDATA necessary for this field? Could the space following the site name cause a mismatch?

**Comment by monbauza** [comment]
Related ticket on HelpScout # 149042

**Comment by Pcosta88** [comment]
See Google News Support thread on this issue: https://productforums.google.com/forum/#!topic/news/LjLGbgU_tZw

**Comment by kakay** [comment]
how a solution to this problem link https://productforums.google.com/forum/#!topic/news/LjLGbgU_tZw

**Comment by tacoverdo** [comment]
Discussed with @jdevalk.
We should just remove the `CDATA` tags from the site name.

**Comment by kakay** [comment]
when fix and update news plugin?

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 153541 when this conversation has been closed.

**Comment by kakay** [comment]
error remains even after the update to version 3.8 is already in check all correspond with the name of the publication google news
