### ISSUE TITLE
WP SEO News, problem with sitemap after update V.3.3

### ISSUE THREAD

**Issue by portalhoy** [Yoast/wpseo-news#222]
Hi this morning i update all the plugins Yoast SEO (free) Video SEO (paid) and the WP SEO News (paid) for some reason i can,t see my news sitemap and the post sitemap show error. 

`This page contains the following errors:

error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.`

URL of all the sitemaps: http://portalhoy.com/sitemap_index.xml
URL of post sitemap: http://portalhoy.com/post-sitemap1.xml (error)
URL of news sitemap: http://portalhoy.com/news-sitemap.xml (nothing showing)

Thanks

Adnan Faisal

**Comment by CarolineGeven** [comment]
Hi @portalhoy, thanks for creating a bug report.  Unfortunately, this is not a bug, but a support request. We use GitHub exclusively for (well-documented) bug reports. However, I took a look at your sitemaps, the errors seem to have gone. To find more information about sitemaps, please refer [to our knowledge base article about blank sitemaps](https://kb.yoast.com/kb/my-sitemap-is-blank-what-s-wrong/).

When you come across an issue such as this and would like support and have a valid license for News SEO, you can contact our [personal support](https://kb.yoast.com/kb/support/#premium).
