### ISSUE TITLE
Jquery tablesorter plugin not loaded

### ISSUE THREAD

**Issue by rensw90** [Yoast/wpseo-news#223]
When viewing the XML News sitemap, a console error is thrown:

![xml_news_sitemap_and_class-sitemaps_php_-_wordpress-seo_-____yoast_vvv_www_wordpress-default_wp-content_plugins_wordpress-seo_](https://cloud.githubusercontent.com/assets/7293908/16111968/60b252d8-33b5-11e6-91bb-76b490e2e8a9.jpg)

Wordpress: 4.5.2
Yoast SEO: 3.3
Yoast News SEO: 3.3
Browser: Firefox

**Comment by CarolineGeven** [comment]
Closing as this issue is not relevant anymore/cannot be reproduced.
