### ISSUE TITLE
[Feature Request] Add ability to disable News SEO Sitemap

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#226]
Users may be comfortable using other sitemap plugins and want to use our plugin for its other features such as Editor's Pick RSS. 

We provide an option in Yoast SEO to disable the sitemaps. Should we then therefore provide users to option to disable _just_ the news-sitemap.xml? Currently, there is no way to disable just the news-sitemap.xml

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 129210 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 238578 when this conversation has been closed.

**Comment by moorscode** [comment]
News SEO is mostly about the news sitemap. Reducing the amount of plugins should be a goal of any customer, thus closing this issue.
