### ISSUE TITLE
Wrong publication date in news sitemap

### ISSUE THREAD

**Issue by monbauza** [Yoast/wpseo-news#227]
The _news:publication_date_ is set to UTC time, however, a wrong time offset is applied (see image below).

When using UTC, the time offset should be +00:00. Instead the time offset corresponding to the local time is outputted (+02:00) leading to a wrong publication time.

As a result, the article appears older in the search results, as if it had been published 2 hours before its actual publication time.

![image](https://cloud.githubusercontent.com/assets/9658774/16558771/3739cab2-41e8-11e6-8912-047c62237be3.png)

Related: https://github.com/Yoast/wpseo-news/issues/112

**Comment by monbauza** [comment]
Please inform the customer of conversation # 130807 when this conversation has been closed.

**Comment by Pcosta88** [comment]
User of the above ticket number reports "It basically sets in the Google results as being UTC. I can site: the site in news and see the correct time. If I look in a site: of Google, it goes 5 hours ago, despite it being 15 minutes or whatever time. It assigns that 5-hour timeframe in the results (news box) and in a site: checking the indexing of post.

So, say I post an article on XYZ. It spiders in both Google News and Google (the in the news box, etc). Instead of listing the time as 10 mins ago, an hour, etc. it will automatically default to 5 hours ago an age from that point"

**Comment by Pcosta88** [comment]
User of the above ticket
" I have UTC-5 set in my general settings:"

**Sitemap time**

![screen shot 2016-07-06 at 3 34 24 pm](https://cloud.githubusercontent.com/assets/8238074/16631831/2dab82d0-438f-11e6-9740-663ab34ad4d9.png)

**Then here's the correct time for the ExoLens post**

![screen shot 2016-07-06 at 3 34 59 pm](https://cloud.githubusercontent.com/assets/8238074/16631840/3955ee86-438f-11e6-8c7a-9d3caf047fa0.png)

**Google News display: User reports "the article was published an hour ago and not six hours ago."**

![news time](https://cloud.githubusercontent.com/assets/8238074/16631876/68675e1c-438f-11e6-878a-9581ff949327.jpg)

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 150604 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
The user from conversation # 150604 provided the following information:

> Here's another example: this time it's showing a post from 3pm (currently
2:15am) as being from 3 days ago, on top of the recent article that was
posted within the last hour as being post 5hrs ago.

![screen shot 2016-10-28 at 2 14 23 am](https://cloud.githubusercontent.com/assets/8946603/19805950/5a68e2c8-9d39-11e6-8ea7-edb055f115c3.png)

**Comment by monbauza** [comment]
Please inform the customer of conversation # 156665 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 162700 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
The user from the conversation # 162700 provided the following information:

> Here's another example with all of the associated information. Post: http://timesofsandiego.com/arts/2016/12/02/san-diego-weekend-guide-dec-2-4/

> News Sitemap Time (correct time and notation)

![image](https://cloud.githubusercontent.com/assets/8946603/20844059/4329f7da-b8e8-11e6-86f6-e55137fec3c2.png)


> Meta Properties (incorrect)

`<meta property="article:published_time" content="2016-12-02T00:05:32-08:00"/>` May be the article was created (9:32 p.m. PST; post time was 12:05 a.m. PST next day).

`<meta property="article:modified_time" content="2016-12-02T07:42:38-08:00"/>` This is the correct modification time (7:42 a.m PST, but notation is 8 hours off).

`<meta property="og:updated_time" content="2016-12-02T07:42:38-08:00" />` Same as above

> Time Class (incorrect)

`<time class="published" datetime="2016-12-02T00:05:32-08:00" title="Friday, December 2nd, 2016, 12:05 am">`

> This may be the time when the article was created (9:32 p.m. PST), but title shows correct
time.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 180448 when this conversation has been closed.

**Comment by Hendy100** [comment]
An awful long time to get such a simple, critical fix done. I wouldn't recommend this plugin based on this alone.

**Comment by CarolineGeven** [comment]
Related https://github.com/Yoast/wordpress-seo/issues/7193

**Comment by monbauza** [comment]
This issue still occurs in News 7.5 and Yoast SEO 7.5.3 (see image below). The publication date in the news- sitemap.xml is wrong (07:58:50+03:00) and doesn't match the lastmod of the post-sitemap.xml (10:58:50+03:00).

![image](https://user-images.githubusercontent.com/9658774/40963329-7ab3fe82-68a8-11e8-9742-1642dbb12bcb.png)

Timezone is set to `Athens` under Settings > General

**Comment by monbauza** [comment]
Please inform the customer of conversation # 379586 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 383562 when this conversation has been closed.
