### ISSUE TITLE
Editor Pick RSS isn't Valid

### ISSUE THREAD

**Issue by iamazik** [Yoast/wpseo-news#241]
### What did you expect to happen?

Editor pick RSS feed would be valid and approve on Google News.
### What happened instead?

While using Portuguese language or any other languages (_not English_), the editor pick RSS feed shows invalid on the Google News and on the [W3C feed validator](https://validator.w3.org/feed/). Google News declined the feed because it is not compliant with RFC 822 standard. Google wants the date/time in English to be compliant with the RFC 822 standard. The following error shows on the W3C feed validator:

`pubDate must be an RFC-822 date-time: Sáb, 07 Jan 12 07:07:21 -0600`

`<pubDate>Sáb, 07 Jan 12 07:07:21 -0600</pubDate>`
### How can we reproduce this behavior?
- Create a new news item
- Mark it as an editor's pick
- Change the site language English to Portuguese or other
- Validate the editor's feed with the [W3C feed validator](https://validator.w3.org/feed/)
### Possible Solution

One of our users were managed to fix the issue by editing our plugin `classes/class-sitemap-editors-pick.php` file on the line: `125`.

`get_the_date( DATE_RFC822 )` to `date("D, d M Y H:i:s O", get_the_date("U"))`

Can you provide a link to a page which shows this issue?
### Technical info
- WordPress version: 4.5.3
- Yoast SEO version: 3.4
- News SEO version: 3.4

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 137063 when this conversation has been closed.
