### ISSUE TITLE
Conflict with Automattic LiveBlog Plugin

### ISSUE THREAD

**Issue by iamazik** [Yoast/wpseo-news#242]
### What did you expect to happen?

No conflict and fatal error while using the News SEO with the Automattic LiveBlog plugin.
### What happened instead?

The following fatal error appears while using the News SEO and [Automattic Liveblog plugin](https://wordpress.org/plugins/liveblog/).

```

Fatal error: Uncaught Error: Call to a member function get() on null in /wp-includes/query.php:28 Stack trace: #0 /wp-content/plugins/liveblog/liveblog.php(415): get_query_var('liveblog') #1 /wp-content/plugins/liveblog/liveblog.php(86): WPCOM_Liveblog::is_entries_ajax_request() #2 /wp-includes/plugin.php(601): WPCOM_Liveblog::add_custom_post_type_support(Object(WP_Query)) #3 /wp-includes/query.php(2493): do_action_ref_array('pre_get_posts', Array) #4 /wp-includes/query.php(4006): WP_Query->get_posts() #5 /wp-includes/query.php(4117): WP_Query->query(Array) #6 /wp-content/plugins/wpseo-news/classes/class-meta-box.php(194): WP_Query->__construct(Array) #7 /wp-content/plugins/wpseo-news/classes/class-meta-box.php(218): WPSEO_News_Meta_Box->standouts_used() #8 /wp-includes/query.php on line 28
```
### How can we reproduce this behavior?
1. Activate the News SEO plugin
2. Activate the Automattic LiveBlog plugin
3. Go to add a new post or page
### Technical info
- WordPress version: 4.5.3
- Yoast SEO version: 3.4.2
- News SEO version: 3.4
- LiveBlog version: 1.5

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 140784 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Possibly related to this: https://github.com/Yoast/wpseo-news/issues/145

**Comment by kevinlisota** [comment]
I had reported this in the [LiveBlog repo as well](https://github.com/Automattic/liveblog/issues/219), though haven't figured out if this is an issue with LiveBlog or SEO News.

**Comment by pacoesni** [comment]
We also report this problem with Yoast and getting no response. I have to unactivate News SEO by Yoast cause tomorrow we're having a Live event. This is really bad for us.

**Comment by monbauza** [comment]
Still happens with Liveblog 1.5.1 and WordPress 4.6.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 146049 when this conversation has been closed.

**Comment by pacoesni** [comment]
I already received a response from Yoast and they told me that they don't when the developer is going to fix this bug. That's frustrating. Today at the WWDC I'll unactivate the plugin by Yoast to be able to use Liveblog, that's really bad.

**Comment by pacoesni** [comment]
This is annoying for a paid plugin. I can't use SEO for News because we covered a lot of events with Liveblog. Unbelievable.

**Comment by moorscode** [comment]
Commented on the Liveblog repo: https://github.com/Automattic/liveblog/issues/219#issuecomment-249520332

**Comment by bfrye26** [comment]
Has there been any updates on a solution? It is a problem I have no solution too, but would love to use both these plugins
