### ISSUE TITLE
PHP Warning While Using the bbPress

### ISSUE THREAD

**Issue by iamazik** [Yoast/wpseo-news#243]
### What did you expect to happen?

No PHP warning on the news sitemap while using bbPress.
### What happened instead?

News sitemap shows the following PHP warning while using bbPress.

`Warning:  in_array() expects parameter 2 to be array, null given in /wp-content/plugins/bbpress/includes/common/functions.php on line 1446`
### How can we reproduce this behavior?
- Go to the news sitemap and view the source code
### Technical info
- WordPress version: 4.6
- Yoast SEO version: 3.4.2
- News SEO version: 3.4

**Comment by mazedulislamkhan** [comment]
It seems the issue was resolved on the News SEO v3.1 and now the issue reappeared. https://github.com/Yoast/wpseo-news/issues/146

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 142958 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 155359 when this conversation has been closed.
