### ISSUE TITLE
3.5 breaks other urls that have the basename "news"

### ISSUE THREAD

**Issue by troyxmccall** [Yoast/wpseo-news#248]
### What did you expect to happen?

To hit my custom-post-type archive called with a slug "news-releases" after upgrading wpseo-news from 3.4 to 3.5

### What happened instead?

Received a failed XML document

### How can we reproduce this behavior?

create a custom post type or page that begins with "news", I replicated by creating a page called "news-home"

Can you provide a link to a page which shows this issue?

Not currently. But I believe the error is due to to this initializer 

https://github.com/Yoast/wpseo-news/commit/a69c711053a16b4f48fddd49be946a6669599d9c#diff-e4d9f60a1ab618ee21622cf5f63f9ac7R63

### Technical info
* WordPress version: 4.6.1
* Yoast SEO version: 3.5

Custom Post Type Archive (news-releases)
![screen shot 2016-09-07 at 4 20 39 pm](https://cloud.githubusercontent.com/assets/129784/18327129/12192fd6-7517-11e6-82ce-8b52919594cb.png)

Page called "News Home"
![screen shot 2016-09-07 at 4 20 32 pm](https://cloud.githubusercontent.com/assets/129784/18327149/2ae8bec8-7517-11e6-9185-215f3b6032a5.png)

**Comment by benvaassen** [comment]
I was able to reproduce the issue. Redirects to the news sitemap: 
![xml_news_sitemap](https://cloud.githubusercontent.com/assets/11910661/18343462/ca7ca2c8-75b3-11e6-8821-e87fc29388de.png)

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 146484 when this conversation has been closed.

**Comment by phylaxis** [comment]
Hey, so we too have encountered this bug. What's the recommended workaround until it's patched? Do we roll back to 3.4 or is there a patch we can safely apply until it's officially patched? If it is to roll back the plug-in where can we just download 3.4 from the repo here?

**Comment by artuze** [comment]
Same here. Happy to see you're on it already.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 146585 when this conversation has been closed.

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 146601 when this conversation has been closed

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 146805 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 146720 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 145711 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 147039 when this conversation has been closed.

**Comment by sandmanspeaking** [comment]
Going back to version 3.4 didn't work for me. Any ideas?

**Comment by amboutwe** [comment]
If rolling back to version 3.4 and the behavior persists, please disable and [enable](https://kb.yoast.com/kb/enable-xml-sitemaps-in-the-wordpress-seo-plugin/#utm_source=support&utm_medium=github&utm_campaign=support-link) the sitemap function. If you have cache, don't forget to clear site cache.

**Comment by artuze** [comment]
FWIW, I tried disabling the WPSEO News plugin completely today and now all I get is a WSOD for the page I'm having trouble with, example.com/newsletter

Not a single thing showing up in debug.log, access.log, error.log to help me troubleshoot.

Interestingly, the only way to fix it is to also disable the base plugin (also at the newest version). Could this issue actually be due to a change in there instead? Maybe a combo of the two?

**Comment by monbauza** [comment]
Please inform the customer of conversation # 147288 when this conversation has been closed.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 147503 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 147756 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 147673 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 147345 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 147547 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 147944 when this conversation has been closed.

**Comment by JiveDig** [comment]
Just hit this bug as well. Rollback to v3.4 fixed for now.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 148005 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 147203 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 148003 when this conversation has been closed.

**Comment by atimmer** [comment]
Hello everyone,

Sorry for not seeing this issue earlier. We are on it and will be releasing 3.5.1 addressing this issue today.

**Comment by atimmer** [comment]
We've just released 3.5.1 to address this issue.
