### ISSUE TITLE
Post-sitempa is blank

### ISSUE THREAD

**Issue by JoshCber** [Yoast/wpseo-news#254]
HI,

Our Post sitemap is blank. generated by Yoast plugin.
Here is the link:
https://www.24point0.com/post-sitemap.xml

When viewed infirefox shows parsing error.
Illegal character

Can anyone please heo me get this fixed?

### Technical info
* WordPress version: 4.6.1
* Yoast SEO version: 3.6.1

**Comment by tacoverdo** [comment]
Works for me. Can you confirm the issue has been resolved?

![xml_sitemap](https://cloud.githubusercontent.com/assets/5147598/19179602/9b362012-8c5f-11e6-940c-9b90dfac0121.png)

**Comment by JoshCber** [comment]
Hi Taco,

Thanks for looking in.
I was pulling my hair yesterday but I had got it resolved. It was an illegal character in one of the image titles.

Thanks,


[cid:image001.png@01D1632C.A3CDF630]

Joshua Nonghuloo
Web & Ecommerce team
Global: +1 217 6364148|India: +91364 2590471
Chillibreeze Solutions Pvt. Ltd., Shillong, India
Watch our Life at Chillibreeze<http://www.chillibreeze.com/ppt-design-experts/> video and how we make a difference to North East India<http://betterwith.office.com/with-office-365-and-sidekick365-ultimate-chillibreeze-brings-technology-and-jobs-to-northeastern-india>





This email and any files transmitted with it are intended for the named recipient(s) only. The information contained in this message may be confidential, legally privileged, or commercially sensitive. If you are not the intended recipient(s), you must not reproduce or distribute any part of the email, disclose its contents to any other party, or take any action in reliance on it. If you have received this email in error, please contact the sender immediately by return email and delete this message from your computer

**Comment by tacoverdo** [comment]
Thanks for your feedback!
