### ISSUE TITLE
[Feature Request] Improve News Sitemap Compatibility with Yandex

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#261]
When the news sitemap is submitted to Yandex errors may be generated such as for news and image tags. This is because the plugin is designed to optimize the site for Google News: https://yoast.com/wordpress/plugins/news-seo/

We should consider making the sitemap more compatible with Yandex.

![screen_shot_2016-11-11_at_3_05_34_pm](https://cloud.githubusercontent.com/assets/8238074/20228684/61c391ac-a820-11e6-82ae-52448909f713.png)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 157357 when this conversation has been closed.

**Comment by jono-alderson** [comment]
Our news sitemaps validate in this tool 👍
