### ISSUE TITLE
ToolSet Custom Post Types fail to display News SEO content

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#264]
### What did you expect to happen?
The plugin would be recognized in the MetaBox. 
### What happened instead?
It was not
### How can we reproduce this behavior?
**1.Create a custom post type using tool set**

**2.See that the News Plugin is not displayed**

![screen_shot_2016-12-09_at_10_38_43_am](https://cloud.githubusercontent.com/assets/8238074/21054732/c4c4f498-bdfc-11e6-881a-dce5083cefa9.png)

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 3.9
* Yoast SEO version: 3.9
* News SEO: 3.9
* ToolSet: 2.2.4

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wpseo-video/issues/374

**Comment by andizer** [comment]
@Pcosta88 We only show the plugin config for post types that are checked under the sitemap settings for news. The custom post type should be checked, this can be done under Yoast SEO -> News SEO and then under `Post Types to include in News Sitemap and Editors' Picks RSS`.
