### ISSUE TITLE
Metabox Tab Not Visible With Video SEO & Disabled Analysis

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-news#266]
### What did you expect to happen?
News tab would appear.

### What happened instead?
News tab doesn't show.

### How can we reproduce this behavior?
Install Yoast SEO (free or prem)
Install both News & Video SEO - Set both to scan posts
Disable both keyword analysis and readability
Create or edit a post, switch to the add-on tab.

### Technical info
* WordPress version: 4.7
* Yoast SEO version: 4.0 (free or prem)
* News SEO version: 4.0
* Video SEO version: 4.0

### Workaround
Enable keyword analysis or readability (or both)

**Comment by atimmer** [comment]
This also breaks on 3.9

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 164559 when this conversation has been closed.

**Comment by iamazik** [comment]
I can confirm this issue still persists on version 4.4

**Comment by andizer** [comment]
This has been fixed in todays release of 4.8.
