### ISSUE TITLE
Perhaps we could do something with the 'Top stories' sometimes shown in google results

### ISSUE THREAD

**Issue by boblinthorst** [Yoast/wpseo-news#272]
When searching on google, you sometimes get to see snippets like these:

*On a search for 'windmill':*

![windmill_-_google_search](https://cloud.githubusercontent.com/assets/11849359/21648037/db029274-d29c-11e6-9a90-0ffbb4943b6b.png)

*On a search for 'star wars':*

![star_wars_-_google_search](https://cloud.githubusercontent.com/assets/11849359/21648577/c27ebbd6-d29e-11e6-89e1-41e1ec62398c.png)

Perhaps we can do something with this in the wpseo-news plugin. One noticable thing though is that the displayed info seems to change bases on browser. (I used firefox and safari to compare).

**Comment by jdevalk** [comment]
Not something we can do anything about.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wpseo-news/issues/179
