### ISSUE TITLE
Fatal error 'yoast_i18n' not found on News SEO settings page

### ISSUE THREAD

**Issue by monbauza** [Yoast/wpseo-news#279]
### What did you expect to happen?
No error to appear on News SEO Settings page (SEO > News SEO)

### What happened instead?
The error below occurs:
`Fatal error: Class 'yoast_i18n' not found in /home/coompone/public_html/prueba-subdomain/wp-content/plugins/wpseo-news/classes/class-admin-page.php on line 73`

### How can we reproduce this behavior?
1. Install Yoast SEO 4.2.1 and News SEO 4.2
2. Go to SEO > News SEO and see the error

### Technical info
* WordPress version: 4.7.2
* Yoast SEO version: 4.2.1
* News SEO version: 4.2

**Comment by monbauza** [comment]
Related https://github.com/Yoast/wordpress-seo-local/issues/773

**Comment by monbauza** [comment]
Please inform the customer of conversation # 177455 when this conversation has been closed.

**Comment by monbauza** [comment]
Related https://github.com/Yoast/wpseo-woocommerce/issues/142

**Comment by iamazik** [comment]
Please inform the customer of conversation # 177583 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 175357 when this conversation has been closed.

**Comment by atimmer** [comment]
We released 4.2.1 to fix this issue.
