### ISSUE TITLE
Post Tags appear as Meta News Keywords in source code

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#281]
### What did you expect to happen?
The Post tags not appear as meta news keywords
### What happened instead?
They appeared
### How can we reproduce this behavior?
**1.Create a post**

**2.Add 5 Post tags**

**3.Add 5 meta news keywords**

![1](https://cloud.githubusercontent.com/assets/8238074/22797409/1fe36ba2-eecc-11e6-9215-01affe7c547f.png)

**4.See post tags appear as meta news keyword in source code**

![2](https://cloud.githubusercontent.com/assets/8238074/22797406/1e3c04d0-eecc-11e6-85e8-ae53356b1239.png)

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 4.7.2
* Yoast SEO version: 4.2.1
* News SEO 4.2.1

**NOTE:** 
If this is expected behavior would there ever be a possible use case that would require Post Tags _to not appear_ as meta news keywords?

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 178635 when this conversation has been closed.

**Comment by Pcosta88** [comment]
related? https://github.com/Yoast/wpseo-news/issues/108

**Comment by simpas810** [comment]
any news, please?

after 1 month.. anything solved?

Thanks
Simone

**Comment by benvaassen** [comment]
This is intended behavior (discussed with @atimmer). However, we should take the tags into account, as explained in #289.
