### ISSUE TITLE
[Feature Request] Provide ability to automatic posting or reposting of news articles based on category

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#284]
We should provide the ability to automatic post or repost news articles based on category.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 181597 when this conversation has been closed.

**Comment by thulshof** [comment]
Thanks for suggesting this feature, but auto-posting or reposting posts isn't a relevant feature for our plugin so we'll close this issue.
