### ISSUE TITLE
News Sitemap Loads When Plugin is Inactive

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-news#287]
### What did you expect to happen?
Inactive News SEO plugin = no news sitemap

### What happened instead?
Inactive News SEO plugin = news sitemap

### How can we reproduce this behavior?
Enable Yoast SEO and News SEO.
Load news sitemap. Works as expected.
Disable News SEO.
Load news sitemap. Works but shouldn't.

### Technical info
* WordPress version: 4.7.3
* Yoast SEO version: 4.4

### Notes
Possibly related #282 

### Work Around
Disable then enable sitemaps in Admin > SEO > XML Sitemaps

**Comment by andizer** [comment]
I cannot reproduce this pull. I guess the bug has been fixed in #283
