### ISSUE TITLE
Red marking when more than 10 news keywords are used doesn't count the tags

### ISSUE THREAD

**Issue by benvaassen** [Yoast/wpseo-news#289]
When I add news keywords to my news post, I get a warning when I use more than 10 keywords (see image1). When I check the source code, I can see that my tags are added there as well (see image2). 

### What did you expect to happen?
I would expect that the limit on the 10 news keywords would take my tags into account because they are added in the news keywords meta tag. 

### What happened instead?
It doesn't count the tags I've added, so I can add 10 meta keywords and have any number of tags. In the source, they all get added to the news keywords (see image2). 

### How can we reproduce this behavior?
1. Create a new post
2. Add 10 tags.
3. Add a few news keywords and see you are not getting any errors. Keep adding news keywords until you have 11 and you will see the error then. 

Image1:
![edit_post_ _dev_wordpress_ _wordpress](https://cloud.githubusercontent.com/assets/11910661/24150645/9b351000-0e46-11e7-9d6d-436e21957019.png)

Image2:
![view-source_local_wordpress_dev_lalala_](https://cloud.githubusercontent.com/assets/11910661/24150706/c87cc10c-0e46-11e7-9293-b65998984ada.png)

Google uses only uses [the first 10 news keywords](https://support.google.com/news/publisher/answer/68297?hl=en). And [this post](http://searchengineland.com/up-close-using-the-news-keywords-tag-for-google-news-140552) seems to imply there is no problem when you exceed 10 meta keywords, but I haven't found any Google documentation. 

### Technical info
* WordPress version: 4.7.3
* Yoast SEO (both free and Premium) version: 4.5
* Yoast SEO News version: 4.5

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 185139 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 206165 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
Closing as this is no longer relevant.
