### ISSUE TITLE
[Feature Request] Provide ability to ping Google when news sitemap is updated

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#291]
We ping Google and Bing when the sitemap updates. https://github.com/Yoast/wordpress-seo/blob/trunk/inc/sitemaps/class-sitemaps.php#L498 

We should provide a notification on the backend that lets users know when Yoast has pinged Google for news sitemap updates.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wordpress-seo/issues/6977

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 190115 when this conversation has been closed.

**Comment by jdevalk** [comment]
No need.
