### ISSUE TITLE
[Feature Request] Add News Sitemap to Main Sitemap file if no News articles have been published

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#294]
Yoast should add the News Sitemap to the Main Sitemap_index.xml file even if no news articles are present on the news sitemap.

![1](https://cloud.githubusercontent.com/assets/8238074/25954657/f88a50ce-3634-11e7-9f50-05958d2ff7fd.png)

![2](https://cloud.githubusercontent.com/assets/8238074/25954662/fa7458e4-3634-11e7-8cb1-d78fae176be8.png)

**This may also affect what appears in a Google Search Console. User may then get confused.**

![3](https://cloud.githubusercontent.com/assets/8238074/25954796/4e5490b4-3635-11e7-8b3e-e9daa5f63049.png)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 195317 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
Google Search Console gives an error when a sitemap is empty and is available in the sitemap_index.xml, for this reason we will not be implementing this.
