### ISSUE TITLE
When a news item is marked as "noindex" using Yoast SEO Or News SEO it should be removed from the sitemap

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#297]
**News SEO has the ability to make it as noindex**

![screen_shot_2017-05-31_at_2_25_19_pm](https://cloud.githubusercontent.com/assets/8238074/26647367/2a8bd74a-460d-11e7-91e1-5be374e01287.png)

** Yoast SEO has the ability to make it a nonindex **

![1](https://cloud.githubusercontent.com/assets/8238074/26558831/b2124306-4479-11e7-9824-69a2389a5eb6.png)

**Using either method, It still shows in the news sitemap.**

![screen shot 2017-05-29 at 2 18 14 pm](https://cloud.githubusercontent.com/assets/8238074/26558843/c299a354-4479-11e7-9787-35ad16a2c260.png)

**We should provide the ability for news items marked as noindex using Yoast SEO and News SEO to be removed from the news sitemap**

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 199220 when this conversation has been closed.

**Comment by jdevalk** [comment]
@PatrickYoast please see whether this still happens, if so, queue it, it's a bug.

**Comment by PatrickYoast** [comment]
This does still happen. The only way to remove a post from the news sitemap is to use the 'Exclude From News Sitemap' option.
 
<img width="730" alt="edit_post_ _awesomesaurus_ _wordpress" src="https://user-images.githubusercontent.com/14159618/35380182-d8ac5fd6-01b8-11e8-9b8b-5580abec1de9.png">

I agree that it would be much more user-friendly (and logical) to automatically exclude a post/page/etc from the news sitemap when it's no-indexed in the first place.

**Comment by andizer** [comment]
While acceptance testing @martijnvaneeghem discovered that the fix for this issue doesn't seem te work. Please take an other look at this to make it work.
