### ISSUE TITLE
No syndication-source meta tag?

### ISSUE THREAD

**Issue by Aaranged** [Yoast/wpseo-news#3]
At a post level, there is an input field labeled "Original Source" that allows you to enter the URL of one or more original news source URLs.

Great - this works fine.  However, Google also supports a syndication-source meta tag:
http://www.google.com/support/news_pub/bin/answer.py?hl=en-GB&answer=191283

It could be that the logic in omitting this option is that "syndication" implies automated consumption and inclusion of a story, and so this meta data field could be addressed at the programmatic level.

However, it is not unusual for a publisher to more-or-less copy and paste a story they find useful to their readers from another source.  As this is a duplicate of an original it seems to me that syndication-source is the appropriate field to populate here, as Google says this tag is "used to distinguish among groups of duplicate identical articles."

The intent of original-source seems more to be reporting or commentary on a story that "broke" at another URL, rather than to indicate that the current post is a copy.  And original-source, at time of writing, is "is only being studied and will not be factored into ranking" - which suggests that is the less useful of the two Google News meta tags.

So it would be great if there were a syndication-source input field available, in addition to the existing original-source input.

**Comment by kevinlisota** [comment]
Any plans to add this tag to WPSEO News?

**Comment by CarolineGeven** [comment]
Closing this as the syndication-source has been deprecated since 2012.
