### ISSUE TITLE
[Feature Request] Provide ability to auto populate/ bulk edit /globally output/  Meta News Keywords

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#303]
**Currently, the only way to add meta news keywords is to add them to each post individually in the field below.**

![screen shot 2017-06-14 at 4 20 09 pm](https://user-images.githubusercontent.com/8238074/27152905-72d36da4-511d-11e7-85da-f0681c3e0bbc.png)

**We should provide a way to bulk edit or globally output or auto-populate those tags (perhaps via a template variable?). We could add a field in the titles and meta section for such variables.**

![screen_shot_2017-06-14_at_4_20_20_pm](https://user-images.githubusercontent.com/8238074/27152951-a4c31b3e-511d-11e7-8b31-bad10cfeeac7.png)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 198123 when this conversation has been closed.

**Comment by jdevalk** [comment]
Seems a bit too spammy for my taste.
