### ISSUE TITLE
[Feature Request] Provide a visual image on the sitemap

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#304]
**When an image is added, it gets counted on the news sitemap:**

![screen_shot_2017-06-22_at_3_39_39_pm](https://user-images.githubusercontent.com/8238074/27452600-283d3438-5761-11e7-8518-e2655c24c78d.png)

**And also appears in the source code**

![screen shot 2017-06-22 at 3 39 48 pm](https://user-images.githubusercontent.com/8238074/27452605-2da1dcd0-5761-11e7-884d-6e8e46bd376c.png)

**However, we should add an image on the sitemap so humans can see it.**

![screen_shot_2017-06-22_at_3_39_39_pm](https://user-images.githubusercontent.com/8238074/27452635-4b5aa5ea-5761-11e7-82db-adc80d7d6680.png)

**This allows users to confirm that XML site maps are use the correct image**

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 203972 when this conversation has been closed.

**Comment by CarolineGeven** [comment]
XML sitemaps are made to be read by search engines. The layout we are using is to make sure it's readable in case a human ever looks at it. However, as it is meant for search engines, we will not be implementing images in the sitemap as this is unnecessary.
