### ISSUE TITLE
[Feature Request] Provide a filter to filter out Post tags

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#305]
Post tags appear as Meta News Keywords. This is intended behavior. However, it may be important to allow an advanced user or specialized SEO person to have
complete control over the tags.

We should create a filter to filter out those post tags.

**NOTE:**
Google uses only uses the first 10 news keywords:https://support.google.com/news/publisher/answer/106259?hl=en&visit_id=1-636462121770773556-2507980735&rd=1. 

And this post: https://searchengineland.com/up-close-using-the-news-keywords-tag-for-google-news-140552 seems to imply there is no problem when you exceed 10 meta keywords, but I haven't found any Google documentation.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wpseo-news/issues/281

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wpseo-news/issues/289

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 206165 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 235929 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 256741 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 178635 when this conversation has been closed.

**Comment by jdevalk** [comment]
We should do this indeed.

**Comment by jdevalk** [comment]
As meta news keywords are gone, this can be closed.
