### ISSUE TITLE
Improve the context of genres

### ISSUE THREAD

**Issue by moorscode** [Yoast/wpseo-news#308]
The genres that can be chosen for the site are not very descriptive.

Google describes them on the following page: https://support.google.com/news/publisher/answer/93992?hl=en

* PressRelease (visible): an official press release.
* Satire (visible): an article which ridicules its subject for didactic purposes.
* Blog (visible): any article published on a blog, or in a blog format.
* OpEd: an opinion-based article which comes specifically from the Op-Ed section of your site.
* Opinion: any other opinion-based article not appearing on an Op-Ed page, i.e., reviews, interviews, etc.
* UserGenerated: newsworthy user-generated content which has already gone through a formal editorial review process on your site.

We should use these descriptions to better inform the user about what the options really mean.

**Comment by jeroenrotty** [comment]
Genres are no longer part of News SEO. Closing.
