### ISSUE TITLE
[Feature Request] Output multiple news-sitemaps if output over 1000 news articles within 48 hours

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#311]
It was mentioned that:

I saw this issue and looked at the documentation Google provides: https://support.google.com/news/publisher/answer/74288?hl=en#sitemapguidelines

There cannot be more than 1000 urls in a sitemap:

> A News Sitemap can contain no more than 1,000 URLs. If you want to include more, you can break these URLs into multiple Sitemaps, and use a Sitemap index file to manage them. Use the XML format provided in the Sitemap protocol. Your Sitemap index file shouldn't list more than 50,000 Sitemaps. These limits help ensure that your web server isn't overloaded by serving large files to Google News.

If the news-sitemap.xml is hard-coded to have ONLY 1000 urls on it, we should develop the ability with the news-sitemap to output these urls into news-sitemap1.xml and news-sitemap2.xml etc.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wpseo-news/issues/137

**Comment by jdevalk** [comment]
Since the news sitemap only contains pages from the last 2 or 3 days (I forget the exact cutoff), and I don't know any major publishers that publish more than 300 articles a _day_, we're going to be safe not doing this.
