### ISSUE TITLE
[Feature Request] Add GoogleBot-News NoFollow tag option

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#317]
**In the News SEO Plugin you can noindex a the news article. This creates a GoogleBot-News noindex tag.**

![screen shot 2017-09-18 at 2 04 03 pm](https://user-images.githubusercontent.com/8238074/30556926-9712c52c-9c7a-11e7-94b9-3e02bcf912a2.png)

**However, if the user wants to nofollow as well, there is not an option to GoogleBot-News nofollow.  A user needs to go to the Yoast SEO to add that option.**

![screen shot 2017-09-18 at 2 04 12 pm](https://user-images.githubusercontent.com/8238074/30556960-b8220b56-9c7a-11e7-9ca9-906f537a0011.png)

**However, when they do that the nofollow is outputted a robots tag NOT a GoogleBot-News tag.**

![screen shot 2017-09-18 at 2 03 43 pm](https://user-images.githubusercontent.com/8238074/30556973-c1b73970-9c7a-11e7-98ce-842a2061834b.png)

**Indeed, Google News themselves seems to imply that a GoogleBot-News "noindex" tag should be accompanied by a GoogleBot-News "nofollow" tag as well here: https://support.google.com/news/publisher/answer/93977?hl=en-GB**

We should consider adding that tag.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wpseo-news/issues/138

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 228001 when this conversation has been closed.

**Comment by jdevalk** [comment]
[Asked John Mueller to clarify](https://twitter.com/jdevalk/status/1042008845239943168), as I don't think this is actually a good idea...

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 525824 when this conversation has been closed.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 561334 when this conversation has been closed.

**Comment by tacoverdo** [comment]
@jdevalk Per John Mueller's response at https://twitter.com/JohnMu/status/1042046798083383297?s=20; what does that mean for this issue?

**Comment by jono-alderson** [comment]
Closing, as this gets wrapped into other News considerations in Jira.
