### ISSUE TITLE
[Feature Request] Provide ability to optimize for Bing News 

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#319]
The News SEO plugin is designed to be optimized for Google News. We say as much here: https://yoast.com/wordpress/plugins/news-seo/

![screen shot 2017-09-27 at 2 38 20 pm](https://user-images.githubusercontent.com/8238074/30931048-8567113e-a391-11e7-9695-db738f8b8570.png)

We should consider providing the ability to optimize for Bing News. Bing has a news section called Bing News PubHub: https://pubhub.bing.com/Home/Welcome

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 234199 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 254944 when this conversation has been closed.

**Comment by jono-alderson** [comment]
Closing, as Bing PubHub inclusion is a manual request system.
