### ISSUE TITLE
Feature request: schema.org/NewsArticle markup tags

### ISSUE THREAD

**Issue by haneef95** [Yoast/wpseo-news#343]
### What did you expect to happen?
The NewsArticle and related schema (AnalysisNewsArticle, BackgroundNewsArticle, OpinionNewsArticle, ReportageNewsArticle, ReviewNewsArticle) to be configurable in wp-admin and thereby appear in the post's source code. 

### What happened instead?
No such option available in wp-admin and tags not appearing in the source code. 

### How can we reproduce this behavior?

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version:
* Yoast SEO version:

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 400354   when this conversation has been closed.

**Comment by omarreiss** [comment]
@haneef95 thanks for this issue. This is definitely something we should add. @jono-alderson could you provide an initial spec for this?

**Comment by mayada-ibrahim** [comment]
Please inform the customer of conversation # 412819 when this conversation has been closed.

**Comment by jono-alderson** [comment]
Scoping in progress over at https://github.com/Yoast/wpseo-news/issues/421

**Comment by mayada-ibrahim** [comment]
Please inform the customer of conversation # 417657 when this conversation has been closed.

**Comment by mayada-ibrahim** [comment]
Please inform the customer of conversation # 476952 when this conversation has been closed.

**Comment by jono-alderson** [comment]
See https://github.com/Yoast/wpseo-news/issues/485

**Comment by jono-alderson** [comment]
This is live, now, and can be customized via our schema API @ https://developer.yoast.com/schema-documentation/api/

**Comment by rmarcano** [comment]
@jono-alderson would it be worth revisiting this, now that we have the new Schema tab that lets you change the Page and Article type? Possibly only for sites using the News SEO plugin?

**Comment by jono-alderson** [comment]
Yep, definitely. Will revisit in Jira :)
