### ISSUE TITLE
Investigate if the meta news_keywords tag is still relevant

### ISSUE THREAD

**Issue by benvaassen** [Yoast/wpseo-news#377]
I was looking at the meta news_keywords tag mentioned on https://yoast.com/wordpress/plugins/news-seo/meta-news_keywords-google-news/

When I click on the official documentation link in that post, I'm not seeing anything on Google's documentation they still use the news_keyword tag.

It seems like Google redid their help center a while back and it's around that time that the documentation on news_keywords disappeared. On the Google support forums, users have been asking the same question in multiple threads. However,  no one seems to know the exact answer as there has been no official statement about it or reply from Google.

**Comment by PatrickYoast** [comment]
Google dropped support for the meta news-keywords
https://searchengineland.com/google-drops-support-meta-news-keywords-tag-292493

**Comment by jdevalk** [comment]
On hold until I get an answer to this question: https://twitter.com/jdevalk/status/973918714658729985

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/yoast.com/issues/2405
