### ISSUE TITLE
[Feature Request] Remove CDATA from News Genre, Title, and News Keywords

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#379]
**News wraps the Title, News Keywords, and News Genres with a CDATA tag:**

![screen shot 2018-02-20 at 11 56 32 am](https://user-images.githubusercontent.com/8238074/36437511-303d9806-1635-11e8-8949-21edd6667c41.png)

**However, Google in there News Sitemap example does not have it:**

https://support.google.com/news/publisher/answer/74288?hl=en

**Removing the CDATA completely will it bring it more inline with Google and create a better user experience as users will not get confused when comparing the Google example to what we currently output.**

**Comment by Pcosta88** [comment]
related  https://github.com/Yoast/wpseo-news/issues/218

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 311559 when this conversation has been closed.

**Comment by jono-alderson** [comment]
Closing; these are intentionally escaped.
