### ISSUE TITLE
Helpcenter is missing

### ISSUE THREAD

**Issue by PatrickYoast** [Yoast/wpseo-news#382]
### What did you expect to happen?
The help center to show up like it does in Yoast SEO

### What happened instead?
The help center is missing and a console error appeared
<img width="1497" alt="news_seo_-_yoast_seo_ _allplugins_test_ _wordpress" src="https://user-images.githubusercontent.com/14159618/37342138-fbae6bac-26c3-11e8-8b81-f446b75224b4.png">

### How can we reproduce this behavior?

1. Install Yoast SEO Premium 7.1 RC2 and News SEO 7.1 RC2.
2. Navigate to the News SEO page.
3. See that help center is missing and find the error in the console (can take a couple of seconds to show up)

Can you provide a link to a page which shows this issue?

The same issue is there for:
Video SEO: https://github.com/Yoast/wpseo-video/issues/577
WooCommerce SEO: https://github.com/Yoast/wpseo-woocommerce/issues/232

### Technical info
* WordPress version: 4.9.4
* Yoast SEO version: 7.1 RC 2

**Comment by Djennez** [comment]
Seems to be working:

![image](https://user-images.githubusercontent.com/34372510/59903288-e38b9f80-9400-11e9-9ae8-8d3b12d7d228.png)

Running The 11.5 RCs
Closing thread.
