### ISSUE TITLE
Google News Genre in meta box has no default button

### ISSUE THREAD

**Issue by Michelle2403** [Yoast/wpseo-news#391]
### What did you expect to happen?
When you're on a specific post, you can choose to override the sitewide default Google News Genre. But once you have clicked in this box, there's no way to go back to the sitewide default option. 

![image](https://user-images.githubusercontent.com/22290584/38368203-f8b78eb4-38e4-11e8-9b67-7f4ef0fc16a7.png)

The option 'none' kind of suggests that the Google News Genre will go back to the sitewide default, but this is not the case. I would suggest adding a default button in the box. 

### Technical info
* WordPress version: 4.9.4
* Yoast SEO version: 7.3 RC1

**Comment by jeroenrotty** [comment]
News genre is no longer in News SEO - closing.
