### ISSUE TITLE
[Feature Request] Provide ability to change stylesheet locations without using a filter

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#394]
We have a filter: `wpseo_sitemap_stylesheet_cache_`  https://github.com/Yoast/wpseo-news/search?utf8=%E2%9C%93&q=stylesheet+filter&type= which apparently is used to set the stylesheet for the sitemap.

Adding the ability from within the plugin to set a specific stylesheet url would improve user experience as user's will not need to write and enter filers. 

**USE CASE**
In some cases a stylesheet may be caught-up in a CDN and providing the ability to override what is being outputted would resolve the issue.

**Comment by PatrickYoast** [comment]
Since the sitemap does not break (only the styling) and the XML sitemap is technically not meant for users to look at, but for search engine web crawlers to crawl we are not doing this.
