### ISSUE TITLE
News Sitemap Contains Articles Older than 2 days or 48 hours

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-news#395]
### What did you expect to happen?
Sitemap would only show articles published within 2 days or 48 hours, per [Google's guidelines](https://support.google.com/news/publisher/answer/74288).

### What happened instead?
Sitemap shows articles published over 48 hours ago.

### How can we reproduce this behavior?

1. Publish a news article immediately.
2. Publish a news article within the last 48 hours.
3. Publish a news article between 49 and 71 hours ago.
4. View sitemap. Articles older than 48 hours appear

### Technical info
* WordPress version: 4.9.5
* Yoast SEO version: 7.2
* Yoast SEO News version: 7.2

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 335691 when this conversation has been closed.

**Comment by jdevalk** [comment]
Fixed by #397
