### ISSUE TITLE
News sitemap is cached, resulting in incorrect sitemaps

### ISSUE THREAD

**Issue by jcomack** [Yoast/wpseo-news#396]
### What did you expect to happen?

I expected posts older than 48 hours to automatically disappear from the sitemap.

### What happened instead?

Post remains, despite it being older than 48 hours. This is due to posts being cached in the sitemap. Whenever you edit a post, said cache is cleared and recreated. However, whenever a post expires in the code (after 48 hours), the cache is never cleared and thus still contains the old post as there's no cronjob (or something else) that recreates the sitemap.

### How can we reproduce this behavior?

* Create a post.
* Open up the News sitemap. See the post is present.
* Change the published date of the newly created post to 49 hours (or more) prior to now in the database (not in WordPress itself).
* Open the News sitemap and see that the old post is still there.
* Bust the cache and reopen the sitemap. Notice the post is now gone.

### Technical info
* WordPress version: 4.9.5
* Yoast SEO version: 7.3

**Comment by jdevalk** [comment]
I don't see this as much of an issue for now, even though it is a "bug", it's also a wontfix as far as I'm concerned.
