### ISSUE TITLE
Travis script needs review as to the running of the unit tests

### ISSUE THREAD

**Issue by jrfnl** [Yoast/wpseo-news#402]
There is something weird going on with the Travis script as the build for PR #401 should fail on **all** PHP versions when run against the second commit, but only the PHP7 versions fail: https://travis-ci.org/Yoast/wpseo-news/builds/378697844

I've tested locally against various PHP 5 versions and the unit tests fail correctly in that case.

As due to the folding, I can't actually see whether the tests are run at all, this is now really difficult to debug.

What I suspect is that the unit tests are currently **not** being run against PHP 5.

/cc @moorscode

**Comment by moorscode** [comment]
I see they are being run, and that a `Fatal` error is occuring, but the status-code of the run is not being caught as expected.

**Comment by jrfnl** [comment]
Hmm... will you handle this one ? I.e. I can let go of it ?

**Comment by moorscode** [comment]
I'll put this in the process for somebody to pick this up.
