### ISSUE TITLE
[Feature Request] Provide ability to disable caching for News Sitemaps

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#408]
Some user's may have PHP issues with the News Sitemap Caching and clearing it. Providing users an easy way to disable it will help make the site run faster and provide a better user experience. 

NOTE: Users may be able to develop the ability using our code base: https://github.com/Yoast/wpseo-news/search?utf8=%E2%9C%93&q=news+sitemap+cache&type=

**Comment by jdevalk** [comment]
I'm not in favor of adding options for this. It should just clear when you publish something that should be in this sitemap.
