### ISSUE TITLE
[Feature Request] Remove Editors' Pick RSS Feed to make plugin more in line with Google

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#409]
Google has dropped support for the Editors' Pick RSS feed. Source:

https://www.seroundtable.com/google-news-kills-editors-picks-standout-meta-tag-25744.html

AND

https://www.blog.google/products/news/new-google-news-ai-meets-human-intelligence/

Dropping the Editors' Pick RSS feed will make the plugin match both Google and user expectations.

**Comment by PatrickYoast** [comment]
@edwintoo Can you make sure we remove the editors pick RSS feed as a feature from the sales page?

**Comment by jdevalk** [comment]
Closed by b26e954dddba1ae528bf1824abc831adc77dc7fa
