### ISSUE TITLE
[Feature Request] Remove Standout Meta Tag to make plugin more in line with Google

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#410]
Google has dropped support for the Standout Meta Tag. Source:

https://www.seroundtable.com/google-news-kills-editors-picks-standout-meta-tag-25744.html

AND

https://www.blog.google/products/news/new-google-news-ai-meets-human-intelligence/

Dropping the Standout Meta Tag will make the plugin match both Google and user expectations.

**Comment by PatrickYoast** [comment]
@edwintoo Can you make sure we remove the standout tag as a feature from the sales page?

**Comment by jdevalk** [comment]
Closed by b26e954dddba1ae528bf1824abc831adc77dc7fa
