### ISSUE TITLE
[Feature Request] Adjust YouTube Videos from showing suggested videos at the end

### ISSUE THREAD

**Issue by diedexx** [Yoast/wpseo-news#412]
_From @Pcosta88 on July 13, 2017 19:14_

**When a video ends suggest non-Yoast SEO videos may appear at the end.** 

![screen shot 2017-07-13 at 3 11 09 pm](https://user-images.githubusercontent.com/8238074/28183574-f0926d4a-67dd-11e7-866b-6c89420eb2e1.png)

**We should change this so we are not accidentally advertising non-Yoast products. A user reports**

> You could set that in youtube video by clicking the share, next click on Embed and them scroll down and uncheck " show suggested videos when the video finishes"

_Copied from original issue: Yoast/kb.yoast.com#80_

**Comment by diedexx** [comment]
_From @siobhanseija on January 24, 2018 10:31_

I've looked into this on the YouTube settings-side, and the user reporting is right, it's not a settings thing. See:

> If you have embedded the video on your site then you could simply disable suggested videos by clicking on 'Embed', then 'Show more', and then un-tick the box labelled 'Show suggested videos when the video finishes'.

It should be fixed by changing these embed settings per video.

**Comment by diedexx** [comment]
The helpcenter is a feature in Yoast SEO. I've forwarded this to the plugin team.

**Comment by diedexx** [comment]
_From @moorscode on January 29, 2018 9:40_

The links are responsible for that, thus this is managed in the shortlinks.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 208325 when this conversation has been closed.

**Comment by jdevalk** [comment]
This is a WP SEO issue, not a news seo issue, there are no videos in news seo at the moment.
