### ISSUE TITLE
Update link to Submit Editors' Picks RSS Feed to Google News

### ISSUE THREAD

**Issue by priscillamc** [Yoast/wpseo-news#413]
### What did you expect to happen?
Clicked the link to submit the RSS feed and be taken to the form to [submit the feed](https://support.google.com/news/publisher/answer/40787?hl=en&ref_topic=4359866#contact=1&ts=3179198).

### What happened instead?
Clicked the link and was redirected to this page: [Contact us for help with Google News](https://support.google.com/news/publisher-center/contact/editors_picks)

### How can we reproduce this behavior?
1. Go to SEO > News SEO
2. Click the link "Submit your Editors' Picks RSS Feed to Google News."

![screenshot_news_1](https://user-images.githubusercontent.com/884156/40681026-fbc3dd42-6355-11e8-9b65-e936554e60f0.png)

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 4.9.6
* Yoast SEO version: SEO Premium 7.5.1, News SEO 7.5

**Comment by priscillamc** [comment]
Please inform the customer of conversation # 375963 when this conversation has been closed.

**Comment by tacoverdo** [comment]
Before we make any changes here, we'll need to test if the link does send you to the right place if your account has been accepted into Google news. 

And even if that isn't the case, the article you suggested is not the right link. There's a difference between sending in your RSS feed (after you've been accepted into Google News) and submitting your site to Google News (aka getting accepted). Your suggestion links to the latter, which is not correct for this link in the plugin.

@PatrickYoast can you please investigate if this link is correct if you're accepted into Google News?

**Comment by PatrickYoast** [comment]
@tacoverdo @priscillamc 

Editors Pick's Feed have been dropped by Google on May 15th 2018. Because of this they have redirected the traffic to the original link to a contact us page.

There are two issues about removing the sections (and links) from News SEO
#409 
#410 

Since there already are issues about this I am closing this issue
