### ISSUE TITLE
[Feature Request] Show only taxonomies associated with the selected post type in the "Post categories to exclude" list

### ISSUE THREAD

**Issue by rmarcano** [Yoast/wpseo-news#415]
We've received a Feature Request regarding the UI of the "Post categories to exclude" section in the News SEO settings.

Right now, all categories are listed on the SEO -> News SEO -> Post categories to exclude list. This can be inconvenient on very large sites with many categories. We've received a request to only list those taxonomies associated to the selected post type.

For example, I've created a Custom Post Type that only has a single category. However, the plugin still lists all available categories on the site (on a [separate issue](https://github.com/Yoast/wpseo-news/issues/414), not even the custom category is shown).

Only those categories available to this Custom Post Type should be shown on the list.

![cpt](https://user-images.githubusercontent.com/1044883/41557017-4f0be792-730a-11e8-88d7-ce1f7709b26d.png)

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 388245  when this conversation has been closed.

**Comment by jdevalk** [comment]
While I understand this would be easier to use, it's a rather complex change, as we'd have to "tie" the first set of checkboxes to the second and i'm honestly not willing to invest that much time. So I'm going to close and deny this.

**Comment by jdevalk** [comment]
Ugh, just seeing the other issue, #414 which is related. Reopening this. I have a solution in mind: we should make this look like the Search Appearance → Content Types tab in Yoast SEO, with toggles for each post type, and when a post type is included, show the taxonomies for that post type underneath.

This needs a design @hedgefield

**Comment by hedgefield** [comment]
Here's what that would look like. Clickable prototype is available at https://sketch.cloud/s/Vk21o/all/page-1/disabled/play

![8e6e6e64-17c0-4da1-b21b-22cc713abbaf](https://user-images.githubusercontent.com/6073772/42275730-93e09bea-7f91-11e8-94df-c88bcfb315bf.png)

**Comment by jdevalk** [comment]
Pull #429 fixes the bug, but doesn't implement the design as that needs someone who can code React and that's not me. @CarolineGeven can you create a separate issue for that?
