### ISSUE TITLE
Changelog doesn't show

### ISSUE THREAD

**Issue by benvaassen** [Yoast/wpseo-news#420]
When an update is available, you can click the "View version x.x details." link to see the changelog: 

![view](https://user-images.githubusercontent.com/11910661/43582407-a31c8740-965c-11e8-9cb5-f7a814d2f30f.png)

For News SEO, the following changelog is shown: 

![changelog](https://user-images.githubusercontent.com/11910661/43582352-6e9ec406-965c-11e8-9211-3f3c4a177741.png)

@herregroen looked into this and the request doesn't go to MyYoast, but instead to WordPress.org. As far as he could see, this should be fixed in the plugin.

**Comment by Jerparx** [comment]
Please inform the customer of conversation # 415430 when this conversation has been closed.

**Comment by jdevalk** [comment]
Created an [issue on MyYoast](https://github.com/Yoast/my-yoast/issues/1974) to fix this.
