### ISSUE TITLE
Add "Article Type" selector to News post options

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/wpseo-news#421]
Proposed Schema markup creates subtypes of `Article`, which includes `NewsArticle` and several descendants thereof (e.g., `Article > NewsArticle > AnalysisNewsArticle`, or `Article > NewsArticle > OpinionNewsArticle`). 

See https://pending.schema.org/NewsArticle (specific subtypes are listed at the end of the page).

Whilst Google claims not to currently use these specifically in a 'visible way', we should anticipate there being future value in adding this kind of markup, and that 'visible' impact isn't necessarily the same as the markup being used anywhere in crawling/indexing/ranking processes.

> "Currently at Google we are generally supportive of the new more detailed NewsArticle subtypes but have nothing published that explicitly uses them in a way that you can see" - https://github.com/schemaorg/schemaorg/issues/1846

We should consider refining the current category selection process, to allow users to add schema markup to their news pages based upon the type of article.

Additionally, as there are likely to be future opportunities around defining what type of _thing_ a specific post is (beyond the context of news - e.g., "this post is a _recipe_"), this feature request gives us an opportunity to experiment and explore before broader consideration of similar functionality. 

### Conflicting / overlapping schemas
The schema types don't quite align with Google's news categories (e.g., Google's categories of `Blog` or `User generated`, vs Schema post types of `ReportageNewsArticle` or `ReviewNewsArticle`).

Additionally, some specific overlap exists - e.g., Schema's `OpinionNewsArticle` markup vs Google's `Opinion` category.

Lastly, some categories don't naturally align with any specific subtype - e.g., a Google news `Press Release` is just a basic `NewsArticle`.

### UI
I'd like to avoid asking the user to classify the post against _two_ seemingly similar, but functionally different dimensions. I wonder if we can simplify the options into a single list, and, in the background, work out the overlap.

That means a single list, asking "What type of news article is this?" (instead of "Google News Genre"), with some humanised options (which might not align specifically to _either_ classification type).

### Examples
- If I select that a post should be considered to be an `Opinion` (currently a _Google News category_), we should apply the logic for both Google News' `Opinion` category, and add the `OpinionNewsArticle` schema.

- If I select that a post should be considered to be a `Review`, we should apply the Google News category of `Opinion`, and add the `ReviewNewsArticle` schema.

- If I select that a post should be considered to be a 'Press Release', we should apply the Google News category of `Press Release`, and simply add standard `NewsArticle` schema.

In all cases where a type isn't specifically any of the new Schema types, we should output `NewsArticle` schema regardless.

### Schema
We should assess each of the new Schema types, and:
- Decide if it makes sense for us to offer support
- Consider it in relation to Google News categories and other Schema types, and fold it into an appropriate option name (e.g., "Review")
- Assess the required and optional markup requirements, and identify which we can/can't extract and provide.

### Gutenberg
This initial exploration currently only considers page-level markup, where our News plugin allows page-level configuration of the news type.

For future-proofing, we should consider that any currently page-level Article type markup should anticipate needing to be able to apply at block-level, too.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wordpress-seo/issues/12026

**Comment by jono-alderson** [comment]
See https://github.com/Yoast/wordpress-seo/issues/10532
