### ISSUE TITLE
Excluding Post Types fails to prevent them from appearing on News Sitemap

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#422]
### What did you expect to happen?
The post type sto NOT appear appear if only one is selected for inclusion
### What happened instead?
The other post types appeared
### How can we reproduce this behavior?

**1.Go to SEO-News and select only one post for inclusion. Note that no categories are selected.**

![screen shot 2018-08-21 at 8 58 30 am](https://user-images.githubusercontent.com/8238074/44402850-ed165380-a520-11e8-92b2-596fd6d3826e.png)

**2.Publish a post type that is excluded**

![screen shot 2018-08-21 at 8 58 39 am](https://user-images.githubusercontent.com/8238074/44402874-ff908d00-a520-11e8-9f48-c15d1f3d841a.png)

**3.See excluded post type appear on sitemap**

![screen_shot_2018-08-21_at_8_58_45_am](https://user-images.githubusercontent.com/8238074/44402900-11723000-a521-11e8-819f-9a6dec008b34.png)

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 4.9.8
* Yoast SEO version: 8.0
* News SEO: 8.0

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 388245 when this conversation has been closed.

**Comment by amboutwe** [comment]
User provided more information:
>line 31 in class-wpseo-news.php seems to be directly related to the problem.
after disabling the line
`'newssitemap_include_post' => 'on',`
the resulting XML sitemap will no longer contain posts.
