### ISSUE TITLE
Fix artifact configuration

### ISSUE THREAD

**Issue by moorscode** [Yoast/wpseo-news#426]
The current configuration of the artifact creation via `grunt` has errors.

The artifact file does not contain a folder and from the last experience on another repository I'm quite sure that there will be files missing or included that should not be there.

The zip created using `grunt artifact` needs to match very closely with the one created with the `create_beta.sh` script in the Wiki repository.

Reference:
https://github.com/Yoast/wordpress-seo/blob/trunk/grunt/config/compress.js#L11

Only after this has been applied and verified can the configuration of News SEO in the https://github.com/Yoast/Wiki/blob/master/includes/product_choice.sh#L76 be changed to include `GRUNT_ARTIFACT="1"`

**Comment by andizer** [comment]
The configuration is fixed in https://github.com/Yoast/Wiki/pull/96. Therefore we can change this option.
