### ISSUE TITLE
jQuery(...).tablesorter is not a function

### ISSUE THREAD

**Issue by IreneStr** [Yoast/wpseo-news#434]
Copied from https://github.com/Yoast/wordpress-seo/issues/6971#issuecomment-423950079 by @ChristophKnopf

> We got this error, too.
>WordPress: 4.9.8
>News SEO: 5.8
>Plugins: unfortunately ... a lot
>
> Steps to reproduce:
>1. in the back end navigate to SEO->News SEO
>2. Click `View your News Sitemap`, new tab should open
>3. Activate your developer tools to get error message (see below)
>
>![image](https://user-images.githubusercontent.com/19904998/45950380-d7a0b780-bfff-11e8-9beb-9580ed8b82df.png)
>
>Tested and reproduced on several OS and browsers. Someone else able to reproduce this?
>
> cheers

**Comment by IreneStr** [comment]
It looks like the tablesorter has been accidentally merged out of wordpress-seo in this commit: https://github.com/Yoast/wordpress-seo/commit/067eb054ebd7964a1897684292e37ecf6bfc1b13.

**Comment by ChristophKnopf** [comment]
@IreneStr updated to 8.3 solved the problem. Sorry that I missed to check for updates 😞

**Comment by IreneStr** [comment]
@ChristophKnopf No problem. I'll close this issue.
