### ISSUE TITLE
Wrong date for news sitemap in sitemap index

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-news#435]
### What did you expect to happen?
The sitemap index would list the correct date format.

### What happened instead?
Wrong date format

### How can we reproduce this behavior?
Install Yoast News 8.3
Set WordPress time zone to UTC
Publish a post
Compare the dates from the index and the newest post in the news sitemap. Correct UTC time on both index and news sitemap.
Change WP time zone to something else.
Disable/Enable the sitemap feature.
Compare the dates from the index and the newest post in the news sitemap. Same date/time but the index still includes the time zone designator which makes it the wrong time.

### Screenshots
News sitemap uses UTC/GMT
![selection_200](https://user-images.githubusercontent.com/8060612/46113420-86cdc200-c1ab-11e8-952d-36b6b3bf5808.png)

Index uses UTC/GMT time but wrong appends time zone designator
![selection_199](https://user-images.githubusercontent.com/8060612/46113438-9ea54600-c1ab-11e8-98a4-43b0c5ed701f.png)

### Technical info
* WordPress version: 4.9.8
* Yoast SEO version: 8.3

Related to recent change? https://github.com/Yoast/wpseo-news/issues/227

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 426977 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 443195 when this conversation has been closed.

**Comment by iamazik** [comment]
The user from the above says the following:

https://github.com/Yoast/wpseo-news/blob/2703a942276a4966faacfa7550fc9dea900a92a7/classes/class-sitemap-item.php#L236

> For a Dutch website, the date should be `UTC+1` or `Europe/Amsterdam` in the above `format_date_with_timezone()` function second parameter. Because of this, the date for all the items in the sitemap is off by one hour.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 443264 when this conversation has been closed.
