### ISSUE TITLE
Post is included in sitemap when no types are enabled

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-news#436]
### How can we reproduce this behavior?
1. Do not include any post types:
<img width="365" alt="screen shot 2018-09-27 at 13 48 16" src="https://user-images.githubusercontent.com/19681708/46143994-0a46ec00-c25c-11e8-8906-6f08a3f6bc3e.png">

2. Create and publish post "newew".
3. Check News Sitemap:
<img width="985" alt="screen shot 2018-09-27 at 14 11 10" src="https://user-images.githubusercontent.com/19681708/46145085-416acc80-c25f-11e8-84c2-3d051a6cdb55.png">

It seems this also comes from #428 .

### Technical info
* WordPress version: 4.9.8
* Yoast SEO version: 8.4 RC1

**Comment by andizer** [comment]
As far as I know this is intended behaviour. There is a fallback in the sitemap code that will enable post when no post types are selected (See https://github.com/Yoast/wpseo-news/blob/trunk/classes/class-wpseo-news.php#L349).

**Comment by dariaknl** [comment]
intended behaviour
