### ISSUE TITLE
Sitemap contains image attachment GUIDs instead of file URLs.

### ISSUE THREAD

**Issue by ChristophKnopf** [Yoast/wpseo-news#438]
### What did you expect to happen?
Correct image URLs <image:loc> of posts in our news-sitemap.xml e.g.:
```
<url>
	...
	<image:image>
		<image:loc>https://bnn.de/wp-content/uploads/2017/08/blaulicht-rss.jpg</image:loc>
		<image:title>blaulicht-rss</image:title>
	</image:image>
</url>
```

### What happened instead?
Google News sitemap contains image attachment GUIDs instead of file URLs, which results in broken image URLs in news-sitemap.xml:
```
<image:loc>http://dpa/weblines/../publishedPictures/large/urn-newsml-dpa-com-20090101-181005-99-248701_large_4_3.jpg</image:loc>
```

### How can we reproduce this behavior?
Import images with uuids of an external service and you will have it.

Can you provide a link to a page which shows this issue?
view-source:https://bnn.de/news-sitemap.xml

### Technical info
* WordPress version: 4.9.7
* Yoast SEO version: 8.3

Proposed solution:
Change https://github.com/Yoast/wpseo-news/blob/trunk/classes/class-sitemap-images.php#L217-L222 to
```
if ( ! empty( $attachment['href'] ) ) {
  $this->images[ $attachment['href'] ] = $image;
}
elseif ( ! empty( $attachment['src'] ) ) {
  $this->images[ $attachment['src'] ] = $image;
}
```
and https://github.com/Yoast/wpseo-news/blob/trunk/classes/class-sitemap-images.php#L245 to
`'href'        => wp_get_attachment_url( $attachment->ID ),`

**Comment by jono-alderson** [comment]
Closing as fixed
