### ISSUE TITLE
Prominent Keywords appear as Terms to Exclude

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#439]
### What did you expect to happen?

Prominent keyword would _not_ appear as a term to exclude. Note, that categories still show-up. 

### What happened instead?

Prominent Keywords appear as Terms to Exclude.

### How can we reproduce this behavior?

**1.Add News SEO**

**2.Create a post with some content.**

 **3.Select Posts (or Pages) and see prominent keywords appear as terms to exclude.**

![screen_shot_2018-10-11_at_8_36_59_am](https://user-images.githubusercontent.com/8238074/46804631-1db08780-cd31-11e8-8d86-d035d63372a0.png)

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 4.9.8
* Yoast SEO version: Yoast SEO Premium 9 RC 1
* News SEO 9 RC1. Not a regression.

**Comment by Pcosta88** [comment]
@moorscode Not sure what you mean. I re-tested this and When you select Posts to Include in News Sitemap, a Prominent Words to exclude section appears. This is odd. I was expected to exclude only categories


![screen_shot_2018-10-11_at_8_36_59_am](https://user-images.githubusercontent.com/8238074/46804561-ee9a1600-cd30-11e8-9d6f-0cdd71a0f9df.png)

**Comment by dariaknl** [comment]
I was able to reproduce it:
- Premium 9.0 RC1 + News 9.0 RC1
