### ISSUE TITLE
Exclude Media type from News Sitemap settings

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-news#448]
### What did you expect to happen?

"Post Types to include in News Sitemap" setting has an option "Media". But Media can receive only `inherit` status and not `publish`. Thus it can be never shown in news sitemap.

It is agreed to remove Media type from "Post Types to include in News Sitemap".

### Technical info
* WordPress version: 4.9.8
* Yoast SEO version: 9.1

**Comment by jono-alderson** [comment]
Closing, and wrapping into some related Jira issues
