### ISSUE TITLE
Jnews Gutenberg Plugin results in inability to select Google News noindex buttons on individual posts/pages

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-news#458]
### What did you expect to happen?

Having the Jnews Gutenberg Plugin would not  result in the inability to select Google News noindex buttons on individual posts/pages

### What happened instead?

Having the Jnews Gutenberg Plugin results in inability to select Google News noindex buttons on individual posts/pages

### How can we reproduce this behavior?
**1.Install the Jnews theme**

**2. Install the Jnews Gutenberg add on** 

**3. Go to post/page**

**4. See that you  are unable to click on the GoogleNews noindex buttons**

![screen shot 2019-01-23 at 10 22 00 am](https://user-images.githubusercontent.com/8238074/51616737-ba6dee00-1ef8-11e9-9d32-669a7140dbfd.png)

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 5.0.3
* Yoast SEO version: 9.5
* News SEO: 9.5
* Jnews theme: 3.1.3 | https://themeforest.net/item/jnews-one-stop-solution-for-web-publishing/20566392
* JNews - Gutenberg : by Jegtheme - 3.0.1 | I am not able to locate the  exact plugin but the changelog shows it. It might be a drop-in with the theme? http://support.jegtheme.com/theme/jnews/

**NOTES:**
No console errors present
Using a child theme does not fix issue

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 466850 when this conversation has been closed.

**Comment by PatrickYoast** [comment]
This is an issue that is not caused by News SEO and therefore not something we can fix.
