### ISSUE TITLE
Change the Schema Article type on News post types

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/wpseo-news#485]
For post types which have been selected as News types, we should alter the Schema `Article` object to a `NewsArticle`. 

See https://github.com/Yoast/wordpress-seo/pull/12456

**Comment by jdevalk** [comment]
> Note that, this should not be done if the article does not contain a (valid*) primary image.

I actually think that should be a separate issue and we should just throw a notice for that. The "having an image" requirement goes for `Article` too.

**Comment by jono-alderson** [comment]
https://github.com/Yoast/wpseo-news/issues/488
