### ISSUE TITLE
404 (Not Found) on admin page on WP 4.9

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-news#505]
### How can we reproduce this behavior?
1. Install and activate News addon 11.2 (11.2-RC1 in my case) on WP 4.9.8.
2. Go to News SEO admin page, you get:
<img width="583" alt="Screenshot 2019-05-20 at 09 57 40" src="https://user-images.githubusercontent.com/19681708/58005372-d0c23a00-7ae5-11e9-99c8-ce686d4b2e01.png">
<img width="676" alt="Screenshot 2019-05-20 at 09 58 43" src="https://user-images.githubusercontent.com/19681708/58005395-de77bf80-7ae5-11e9-81ca-642de0cedcaf.png">

It does not seem to have a further impact.
The issue **IS NOT** reproduced on WP 5.2

### Technical info
* WordPress version: 4.9.8
* Yoast SEO version: 11.2.1

**Comment by IreneStr** [comment]
Closing because it doesn't break anything, and is only present in 4.9.
