### ISSUE TITLE
Metabox tab content of wpseo news is missing styling

### ISSUE THREAD

**Issue by Djennez** [Yoast/wpseo-news#527]
### What did you expect to happen?
The contents of the `Google News` tab in our metabox to be styled correctly.

### What happened instead?
Styles are either missing or wrongly applied. It is inconsistent with the styling of the rest of the tabs. Other add-on plugins don't exhibit this behavior (video is fine).

### How can we reproduce this behavior?
1. Install Yoast Premium 11.9-RC1
2. Install wpseo-news 11.9-RC2
3. Create or edit a post
4. Open the newly added `Google News` tab in our metabox
5. notice the styling (padding) is missing / wrong.

Screenshot:
![image](https://user-images.githubusercontent.com/34372510/62549144-42e62780-b868-11e9-9d49-e54f2cfe9020.png)

### Technical info
* WordPress version: 5.2.2
* Yoast SEO version: 11.9-RC1
* This is regression from 11.8

**Comment by IreneStr** [comment]
This didn't fix it: https://github.com/Yoast/wpseo-news/commit/cec2ae4e369e0b4fa794d98c53e894ad36643f2e

**Comment by afercia** [comment]
Question:
why SEO News uses a `.sass` file (which needs to be compiled for just one CSS ruleset with just one css property) and SEO Video uses normal `.css` files?
