### ISSUE TITLE
Add a toggle to switch from excluding to including News content

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/wpseo-news#537]
The News plugin allows users to specify which types of content should be considered as 'news'. This determines whether or not those posts/pages are included in XML sitemaps, modifies their schema output, and also adjusts their meta information.

We manage this by allowing users to _exclude_ certain post types or taxonomies.

E.g., 
![image](https://user-images.githubusercontent.com/11629607/64174840-5df18a80-ce5a-11e9-9249-a6c1e0aedc7a.png)

## The problem

In some cases, a site may be configured in such a way that all news content is a `post`, in a particular `category`.

For the initial configuration, this can be frustrating and require lots of clicking, particularly if there are many (sometimes hundreds) of categories. I must tick every category _except_ for my news category.

More significantly, **every time site editor(s) add a new category, a user (with SEO privileges) must manually exclude that category**. This causes problems (non-news is temporarily marked and submitted as news), and there's no workflow management here for setups which rely on user roles.

### Large sites
Some particularly large websites (many news publishers, in fact) have news content which spans hundreds/thousands of categories, and they continue to add more categories over time. This makes our current exclusion-based approach cumbersome for large sites (verging on un-useable).

In an ideal world, news content would be constrained to a particular post type, and therefore an exclusion-based approach doesn't need to continually scale. However, many sites aren't built like this, and use categories-of-posts.

## A solution

We should, therefore, add the ability to switch to an inclusion-based approach _in each section of our options_ (defaulting to exclude, as per current behaviour).

NB: I considered an 'include OR exclude' model, but managing this becomes technically and conceptually complex (i.e., it's unclear whether they should be mutually exclusive, etc).

Here's a quick mockup of adding an 'Include/Exclude' switch.

![image](https://user-images.githubusercontent.com/11629607/64168933-ebc67900-ce4c-11e9-8ce1-ced864773f37.png)

We may also wish to tweak some of the text/headings to make the purpose/function of these options clear.

Also solves https://github.com/Yoast/wpseo-news/issues/497

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wpseo-news/issues/537

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wpseo-news/issues/415

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 568735 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 636313 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 639890  when this conversation has been closed.

**Comment by josh-yoast** [comment]
Please inform the customer of conversation # 682614 when this conversation has been closed.

**Comment by jono-alderson** [comment]
Moved to Jira: https://yoast.atlassian.net/browse/PROD-331
