### ISSUE TITLE
Integrate with WPSEO_Options

### ISSUE THREAD

**Issue by andizer** [Yoast/wpseo-news#548]
Integrate with the `WPSEO_Options` framework and make sure option modification is done by using the `get` and `set` methods from `WPSEO_Options`

We should use the `register_option` (from: https://github.com/Yoast/wordpress-seo/pull/13689) to register the option to the framework.

- [x] Makes an options class that represents wpseo news specific options (must extend `WPSEO_Option`
- [x] Register the option `WPSEO_Options::register_option`.
    - [x] Rename `version` to `news_version`
- [x] Retrieve values from the options by using `WPSEO_Options::get`
- [x] Modify option values by `WPSEO_Options::set`
- [x] Unittest as far as possible
- [x] Check if https://github.com/Yoast/wordpress-seo/issues/14082 is fixed by this

**Comment by maartenleenders** [comment]
LGTM, but there were quite a lot of changes so it's possible I missed something 🤔

**Comment by IreneStr** [comment]
Fixed in https://github.com/Yoast/wpseo-news/pull/591
