### ISSUE TITLE
Google recently updated their requirements for news sites/feeds: improve RSS feed(s)

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/wpseo-news#582]
Google recently updated their requirements for news sites/feeds.
See https://webmasters.googleblog.com/2019/12/google-publisher-center.html

There's a clear direction from Google that they want to rely more on feed-based consumption, rather than XML-based consumption.

An investigation has highlighted that there are some gaps between how WordPress structures/outputs feeds vs those requirements - and that our News plugin only closes _some_ of those gaps.

We should make improvements to our News solution to make sure that feeds align with Google's requirements.

## Critical technical improvements

- [ ] Update the `pubDate` value whenever a post/page is updated (note that this should _not_ affect the sort/display order of the feed).

- [ ] Restrict permitted HTML tags in the `<content:encoded>` node to: `<h1>` through `<h6>`, `<br>`, `<ol>`, `<ul>`, `<li>`, `<a>`, `<p>`, `<blockquote>`, `<cite>`, `<b>`, `<strong>`, `<i>`, `<em>`, `<img>`, `<figure>`, `<figcaption>`, `<span>`, `<iframe>`, `<div>`.
 

- [ ] If a post has a featured image, then:

  - [ ] Add it into the top of the post content (using  `<figure>` - optionally `<figcaption>`  as appropriate - markup).

  - [ ] Add a `class="type:primaryImage"` attribute to the `<img>` tag.

## Desirable technical enhancements
- [ ] HTML transformations

  - [ ] Transform curly/special quotes into normal quotes.

  - [ ] Remove empty paragraph tags (`<p></p>`).

  - [ ] Remove excessive/concurrent linebreaks between paragraphs/blocks.
- [ ] Remove the `<description>` node (this is dropped by Google if/when shorter than the `<content:encoded>` node).

- [ ] Add an `<author>` node, containing the 'full name' of the user (e.g., `<author>Jono Alderson</author>`); _only_ when the user _firstname_ and _lastname_ are defined.

**Comment by Pcosta88** [comment]
See also:

https://support.google.com/news/publisher-center/answer/9545549?hl=en&ref_topic=9606804

https://support.google.com/news/publisher-center/answer/9545245

**Comment by rmarcano** [comment]
Google News also requires that sites add the full content of posts to the feed. Related FR: https://github.com/Yoast/featurerequests/issues/396

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 574338 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 581207 when this conversation has been closed.

**Comment by priscillamc** [comment]
Please inform the customer of conversation # 612127  when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 642656 when this conversation has been closed.

**Comment by rumejan** [comment]
Please inform the customer of conversation # 664776 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 667279 when this conversation has been closed.

**Comment by jono-alderson** [comment]
Moved to Jira.

**Comment by iamazik** [comment]
Moved to https://yoast.atlassian.net/browse/PROD-330
