### ISSUE TITLE
Difference between meta news_keywords and XML sitemap keywords

### ISSUE THREAD

**Issue by jdevalk** [Yoast/wpseo-news#60]
This is slightly annoying but meta news_keywords are "free form", whereas for the XML News sitemap it's best to (at least partially) adhere to [this list](https://support.google.com/news/publisher/answer/116037?hl=en&ref_topic=2527688). 

We should probably split the two, it would be best if we can add some sort of auto suggest for that.

**Comment by CarolineGeven** [comment]
Closing as no longer relevant
