### ISSUE TITLE
Testing indexables: checkbox in News tab misaligned

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-news#624]
I doubt if this issue is introduce within indexables, but as it was agreed during testing of indexables we compare current production version with indexables version. It seems, this issue may have the same cause as https://github.com/Yoast/wordpress-seo/issues/14629

This is how checkbox look like in 13.3:

<img width="416" alt="Screenshot 2020-03-30 at 08 21 34" src="https://user-images.githubusercontent.com/19681708/77881535-7d6d5c00-725f-11ea-929f-7b0428a50cdd.png">

In indexables version checkbox seems to be misaligned:
<img width="459" alt="Screenshot 2020-03-30 at 08 16 07" src="https://user-images.githubusercontent.com/19681708/77881558-8a8a4b00-725f-11ea-8c86-4f28a2e740b1.png">

**Comment by IreneStr** [comment]
Fixed in Yoast/wordpress-seo/pull/14697
