### ISSUE TITLE
Genres in the plugin vs categories in Google News

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-news#63]
When signing up for Google News, one can choose from the following categories:
![contact_us_-_news_help](https://cloud.githubusercontent.com/assets/5147598/2778809/faa06928-caf5-11e3-8469-7574dc071572.png)

In our plugin we offer the following default genres:
![yoast_wordpress_seo__news_seo__theme__wordpress](https://cloud.githubusercontent.com/assets/5147598/2778826/20de68f6-caf6-11e3-8ffd-614157781a46.png)

@barrykooij & @jdevalk, shouldn't those be equal?

**Comment by moorscode** [comment]
The "genres" support page lists the options we currently offer (https://support.google.com/news/publisher/answer/93992?hl=en), mind that multiple genres can apply to the tag.

![content_types_-_news_help](https://user-images.githubusercontent.com/2005352/28466499-eaf85390-6e2c-11e7-9d3a-e621b7c771ed.png)

---

The Google News subscription method currently offers this list of options:
![news_-_home](https://user-images.githubusercontent.com/2005352/28466330-59995db8-6e2c-11e7-8ac7-716e229f1311.png)
(See https://partnerdash.google.com/partnerdash/d/news#p:id=pfehome)

But it seems like these are configuration settings in the "Google News Publisher Center" and not options to provide on the site as meta value.
See https://support.google.com/news/publisher/answer/4582731

---

Closing this issue based on the information found.
