### ISSUE TITLE
No validation of ampersands by field news_sitemap_name

### ISSUE THREAD

**Issue by 3ele-projects** [Yoast/wpseo-news#753]
### What did you expect?
The validation of the Google News Publication Name field after entering Ampersand (&) to Escape Code ( &amp;) according to the standard:

https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap 

### What happened instead?

No validation of the field, broken sitemap, error message in Google.

### How can we reproduce this behaviour?

Inserting an ampersand in the field news_sitemap_name  /  wp-admin/admin.php?page=wpseo_news

### Can you provide a link to a page that shows this problem?

not necessary, can be reproduced.

### Technical information

* WordPress version: 6.0
* Yoast SEO Version: 19.2
* Yoast SEO News Version: 13.1

**Comment by jeroenrotty** [comment]
Please inform the customer of conversation # 622242 when this conversation has been closed.

**Comment by jeroenrotty** [comment]
Please inform the customer of conversation # 691458 when this conversation has been closed.

**Comment by jeroenrotty** [comment]
Please inform the customer of conversation # 735080 when this conversation has been closed.

**Comment by jeroenrotty** [comment]
Please inform the customer of conversation # 927275 when this conversation has been closed.

**Comment by jeroenrotty** [comment]
Please inform the customer of conversation # 993464 when this conversation has been closed.

**Comment by jeroenrotty** [comment]
Please inform the customer of conversation # 1007773 when this conversation has been closed.

**Comment by enricobattocchi** [comment]
Fixed by #788
