### ISSUE TITLE
News PHP notice/warning on activation

### ISSUE THREAD

**Issue by jeroenrotty** [Yoast/wpseo-news#805]
Moved from: https://yoast.atlassian.net/browse/IM-1943
Reporter: @oksanayoast 

### Description
Install and activate Query Monitor
Install and activate Yoast SEO Free 20.6
Install and activate Yoast SEO: News 13.1
Check PHP errors in Query Monitor

Actual result:  “Trying to access array offset on value of type bool “ PHP notice/warning.

```
/mnt/plugins/wpseo-news/classes/upgrade-manager.php:36
WPSEO_News_Upgrade_Manager->check_update()
/mnt/plugins/wpseo-news/classes/wpseo-news.php:111
WPSEO_News->init_admin()
/mnt/plugins/wpseo-news/classes/wpseo-news.php:57
WPSEO_News->__construct()
/mnt/plugins/wpseo-news/wpseo-news.php:61
__wpseo_news_main()
wp-includes/class-wp-hook.php:308
do_action(‘plugins_loaded’)
wp-settings.php:486
```

**Comment by jeroenrotty** [comment]
Please inform the customer of conversation # 960383 when this conversation has been closed.

**Comment by jeroenrotty** [comment]
Please inform the customer of conversation # 965563 when this conversation has been closed.

**Comment by Yvonne-Palanca** [comment]
Please inform the customer of conversation # 1022139 when this conversation has been closed.

**Comment by enricobattocchi** [comment]
- apply defensive coding to the line triggering the error:
`wpseo-news/classes/upgrade-manager.php:36`
```
if ( version_compare( WPSEO_News::VERSION, $options['news_version'], '>' ) ) {
```
- make sure that by skipping the upgrade routines in case $options['news_version'] is not set we are not breaking any feature

**Comment by VictoriaMcCarter** [comment]
Please inform the customer of conversation # 1027662 when this conversation has been closed.
