### ISSUE TITLE
Errors in WP Debug for WPSEO_News_Meta_Box::get_meta_boxes()

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-news#81]
As reported in https://github.com/Yoast/wordpress-seo/issues/1304.

When working with WP debug on, get the following error:

``` php
Strict Standards: Declaration of WPSEO_News_Meta_Box::get_meta_boxes() should be compatible 
with WPSEO_Metabox::get_meta_boxes($post_type = 'post') in 
/path/to/site.com/wp-content/plugins/wpseo-news/classes/class-meta-box.php on line 3
```

A quick fix is to add the function parameter from the WP SEO version of the method:

wpseo-news/classes/class-meta-box.php, line 16:
`public function get_meta_boxes( $post_type = 'post') {`

Not a huge deal but it's another error message in debug when someone might be troubleshooting another issue.

**Comment by CarolineGeven** [comment]
This does not seem relevant anymore. Probably fixed with the 3.0 release, therefore closing this.
