### ISSUE TITLE
Wordpress 6.4 Compatiblity

### ISSUE THREAD

**Issue by coolrecep** [Yoast/wpseo-news#835]
The plugin broke the mobile website. When do you plan to update it? Is this a dead software?

**Comment by josevarghese** [comment]
Hi @coolrecep 

The plugin is compatible with WordPress 6.4, and we didn't notice any issues. So, can you please share more details about the issue you are facing to check this further?

**Comment by coolrecep** [comment]
Turns out to be a problem with our NewsMag theme. Thanks.

**Comment by josevarghese** [comment]
Thanks for letting us know @coolrecep :)

Have a great day!
