### ISSUE TITLE
Move News SEO down in SEO menu in the admin

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-news#85]
News SEO should be at the bottom of the submenu-items, like Local SEO and Video SEO.

**Comment by jdevalk** [comment]
Agreed, those should be in alphabetical order so let's fix that.

**Comment by Petervw** [comment]
I am not be able to reproduce this issue, the "News SEO" sub-item was already placed below the "Extensions" item.

WordPress SEO version: 2.1.1
News SEO version: 2.2.3

**Comment by jdevalk** [comment]
:+1:

**Comment by CarolineGeven** [comment]
Closing this as this issue seems already fixed in the current versions. If not, please create a new issue.
